import { Chapter, Lesson, Question } from '../types';

// =========================================================================
// 1. TOÀN BỘ 21 CHƯƠNG TOÁN THPT (LỚP 10, 11, 12) - KẾT NỐI TRI THỨC
// =========================================================================
export const FULL_CHAPTERS: Chapter[] = [
  // --- LỚP 12 (6 Chương) ---
  {
    id: 'chap-12-1',
    grade_id: 12,
    name_vi: 'Chương I. Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số',
    name_en: 'Chapter I. Applications of Derivatives to Function Analysis',
    description: 'Tính đơn điệu, cực trị, GTLN-GTNN, tiệm cận, khảo sát hàm số và bài toán tối ưu thực tế',
    order_index: 1,
  },
  {
    id: 'chap-12-2',
    grade_id: 12,
    name_vi: 'Chương II. Vectơ và hệ toạ độ trong không gian',
    name_en: 'Chapter II. Vectors and Coordinate Systems in 3D Space',
    description: 'Vectơ trong không gian, toạ độ Oxyz, tích vô hướng, tích có hướng và ứng dụng định vị thực tế',
    order_index: 2,
  },
  {
    id: 'chap-12-3',
    grade_id: 12,
    name_vi: 'Chương III. Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm',
    name_en: 'Chapter III. Measures of Dispersion for Grouped Data',
    description: 'Khoảng biến thiên, khoảng tứ phân vị, phương sai, độ lệch chuẩn và phân tích rủi ro tài chính',
    order_index: 3,
  },
  {
    id: 'chap-12-4',
    grade_id: 12,
    name_vi: 'Chương IV. Nguyên hàm và tích phân',
    name_en: 'Chapter IV. Antiderivatives and Integrals',
    description: 'Bảng nguyên hàm, phương pháp tích phân, diện tích hình phẳng, thể tích khối tròn xoay và vật lý',
    order_index: 4,
  },
  {
    id: 'chap-12-5',
    grade_id: 12,
    name_vi: 'Chương V. Phương pháp toạ độ trong không gian (Oxyz)',
    name_en: 'Chapter V. Coordinate Geometry Methods in Space',
    description: 'Phương trình mặt phẳng, đường thẳng, mặt cầu và mô hình dẫn đường bay thực tế',
    order_index: 5,
  },
  {
    id: 'chap-12-6',
    grade_id: 12,
    name_vi: 'Chương VI. Xác suất có điều kiện',
    name_en: 'Chapter VI. Conditional Probability and Bayes Formula',
    description: 'Xác suất có điều kiện, công thức xác suất toàn phần, công thức Bayes trong y tế và công nghệ',
    order_index: 6,
  },

  // --- LỚP 11 (8 Chương) ---
  {
    id: 'chap-11-1',
    grade_id: 11,
    name_vi: 'Chương I. Hàm số lượng giác và phương trình lượng giác',
    name_en: 'Chapter I. Trigonometric Functions and Equations',
    description: 'Góc lượng giác, hàm số lượng giác, phương trình lượng giác cơ bản và dao động sóng thực tế',
    order_index: 1,
  },
  {
    id: 'chap-11-2',
    grade_id: 11,
    name_vi: 'Chương II. Dãy số. Cấp số cộng và cấp số nhân',
    name_en: 'Chapter II. Sequences, Arithmetic and Geometric Progressions',
    description: 'Dãy số, cấp số cộng, cấp số nhân, bài toán lãi kép ngân hàng và mô hình tăng trưởng dân số',
    order_index: 2,
  },
  {
    id: 'chap-11-3',
    grade_id: 11,
    name_vi: 'Chương III. Các số đặc trưng đo xu thế trung tâm của mẫu số liệu ghép nhóm',
    name_en: 'Chapter III. Measures of Central Tendency for Grouped Data',
    description: 'Số trung bình, trung vị, tứ phân vị, mốt và ứng dụng thống kê kinh tế xã hội',
    order_index: 3,
  },
  {
    id: 'chap-11-4',
    grade_id: 11,
    name_vi: 'Chương IV. Quan hệ song song trong không gian',
    name_en: 'Chapter IV. Parallel Relationships in 3D Space',
    description: 'Đường thẳng song song, mặt phẳng song song, phép chiếu song song trong kiến trúc xây dựng',
    order_index: 4,
  },
  {
    id: 'chap-11-5',
    grade_id: 11,
    name_vi: 'Chương V. Giới hạn. Hàm số liên tục',
    name_en: 'Chapter V. Limits and Continuous Functions',
    description: 'Giới hạn dãy số, giới hạn hàm số, tính liên tục và vận tốc chuyển động tức thời',
    order_index: 5,
  },
  {
    id: 'chap-11-6',
    grade_id: 11,
    name_vi: 'Chương VI. Hàm số mũ và hàm số lôgarit',
    name_en: 'Chapter VI. Exponential and Logarithmic Functions',
    description: 'Luỹ thừa, logarit, phương trình mũ-logarit, độ pH hoá học và động đất độ Richter',
    order_index: 6,
  },
  {
    id: 'chap-11-7',
    grade_id: 11,
    name_vi: 'Chương VII. Đạo hàm',
    name_en: 'Chapter VII. Derivatives',
    description: 'Ý nghĩa hình học, vật lý của đạo hàm, quy tắc tính đạo hàm và tốc độ biến thiên thực tế',
    order_index: 7,
  },
  {
    id: 'chap-11-8',
    grade_id: 11,
    name_vi: 'Chương VIII. Quan hệ vuông góc trong không gian',
    name_en: 'Chapter VIII. Orthogonality in Spatial Geometry',
    description: 'Đường thẳng vuông góc mặt phẳng, góc và khoảng cách trong không gian kiến trúc',
    order_index: 8,
  },

  // --- LỚP 10 (7 Chương) ---
  {
    id: 'chap-10-1',
    grade_id: 10,
    name_vi: 'Chương I. Mệnh đề và tập hợp',
    name_en: 'Chapter I. Propositions and Sets',
    description: 'Mệnh đề toán học, các phép toán tập hợp và logic ứng dụng trong lập trình tin học',
    order_index: 1,
  },
  {
    id: 'chap-10-2',
    grade_id: 10,
    name_vi: 'Chương II. Bất phương trình và hệ bất phương trình bậc nhất hai ẩn',
    name_en: 'Chapter II. Linear Inequalities and Systems in Two Variables',
    description: 'Miền nghiệm trên toạ độ Oxy và bài toán quy hoạch tuyến tính tối ưu lợi nhuận kinh doanh',
    order_index: 2,
  },
  {
    id: 'chap-10-3',
    grade_id: 10,
    name_vi: 'Chương III. Hệ thức lượng trong tam giác',
    name_en: 'Chapter III. Trigonometric Relations in Triangles',
    description: 'Định lý côsin, định lý sin, công thức Heron và đo đạc khoảng cách địa lý thực địa',
    order_index: 3,
  },
  {
    id: 'chap-10-4',
    grade_id: 10,
    name_vi: 'Chương IV. Vectơ và các phép toán',
    name_en: 'Chapter IV. Vectors and Operations',
    description: 'Tổng hiệu vectơ, tích vô hướng và bài toán hợp lực, công cơ học trong vật lý',
    order_index: 4,
  },
  {
    id: 'chap-10-5',
    grade_id: 10,
    name_vi: 'Chương V. Các số đặc trưng đo xu thế trung tâm và mức độ phân tán',
    name_en: 'Chapter V. Measures of Central Tendency and Dispersion',
    description: 'Số gần đúng, sai số đo lường, số trung bình, phương sai và độ lệch chuẩn',
    order_index: 5,
  },
  {
    id: 'chap-10-6',
    grade_id: 10,
    name_vi: 'Chương VI. Hàm số, đồ thị và ứng dụng',
    name_en: 'Chapter VI. Functions, Graphs and Applications',
    description: 'Hàm số bậc hai, đồ thị Parabol, dấu tam thức bậc hai và bài toán quỹ đạo bay thực tế',
    order_index: 6,
  },
  {
    id: 'chap-10-7',
    grade_id: 10,
    name_vi: 'Chương VII. Phương pháp toạ độ trong mặt phẳng',
    name_en: 'Chapter VII. Coordinate Geometry in the Plane',
    description: 'Toạ độ Oxy, phương trình đường thẳng, đường tròn, ba đường conic (Elip, Hyperbol, Parabol)',
    order_index: 7,
  },
];

// =========================================================================
// 2. TOÀN BỘ CÁC BÀI HỌC VÀ DẠNG TOÁN KÈM ỨNG DỤNG THỰC TẾ (LỚP 10, 11, 12)
// =========================================================================
export const FULL_LESSONS: Lesson[] = [
  // =========================================================================
  // LỚP 12: CHƯƠNG I - ỨNG DỤNG ĐẠO HÀM
  // =========================================================================
  {
    id: 'les-12-1-1',
    chapter_id: 'chap-12-1',
    topic_id: 'top-12-1-1',
    title_vi: 'Bài 1. Tính đơn điệu và cực trị của hàm số',
    title_en: 'Lesson 1. Monotonicity and Extrema of Functions',
    order_index: 1,
    learning_objectives: [
      'Hiểu và vận dụng dấu của đạo hàm $f\'(x)$ để xét tính đồng biến, nghịch biến',
      'Xác định điểm cực đại (Local Maximum) và điểm cực tiểu (Local Minimum)',
      'Giải quyết các bài toán chứa tham số $m$ và bài toán tối ưu tốc độ tăng trưởng',
    ],
    vocabulary_list: ['Strictly Increasing', 'Strictly Decreasing', 'Local Extrema', 'Derivative', 'Variation Table', 'Critical Points'],
    key_concepts_vi: `• $f'(x) > 0$ trên $K \\implies f(x)$ đồng biến trên $K$; $f'(x) < 0$ trên $K \\implies f(x)$ nghịch biến trên $K$.\n• Điểm cực trị: $f'(x_0) = 0$ (hoặc không xác định) và $f'(x)$ đổi dấu qua $x_0$.\n• Điều kiện cực trị theo đạo hàm cấp hai: $f'(x_0)=0, f''(x_0)<0 \\implies x_0$ là điểm Cực đại; $f''(x_0)>0 \\implies x_0$ là điểm Cực tiểu.`,
    key_concepts_en: `• $f'(x) > 0$ on $K \\implies f$ strictly increasing; $f'(x) < 0$ on $K \\implies f$ strictly decreasing.\n• $x_0$ is a local extremum point if $f'(x)$ changes sign as $x$ passes through $x_0$.\n• Second derivative test: $f'(x_0) = 0, f''(x_0) < 0 \\implies$ Local Maximum; $f''(x_0) > 0 \\implies$ Local Minimum.`,
    formulas: [
      "f'(x) > 0 \\implies \\text{Hàm số đồng biến (Increasing)}",
      "f'(x) < 0 \\implies \\text{Hàm số nghịch biến (Decreasing)}",
      "f'(x_0) = 0 \\land f''(x_0) < 0 \\implies x_0 \\text{ là điểm cực đại (Local Max)}",
      "f'(x_0) = 0 \\land f''(x_0) > 0 \\implies x_0 \\text{ là điểm cực tiểu (Local Min)}",
    ],
    types: [
      {
        id: 'type-12-1-1',
        lesson_id: 'les-12-1-1',
        code: 'Dạng 1',
        title_vi: 'Tìm khoảng đơn điệu của hàm số',
        title_en: 'Determine Intervals of Increase and Decrease',
        order_index: 1,
        sample_count_tn: 2,
        sample_count_ds: 1,
        sample_count_tln: 1,
        sample_count_tl: 1,
      },
      {
        id: 'type-12-1-2',
        lesson_id: 'les-12-1-1',
        code: 'Dạng 2',
        title_vi: 'Tìm cực trị của hàm số đa thức và hàm phân thức',
        title_en: 'Find Local Extrema of Polynomial and Rational Functions',
        order_index: 2,
        sample_count_tn: 2,
        sample_count_ds: 1,
        sample_count_tln: 1,
        sample_count_tl: 1,
      },
      {
        id: 'type-12-1-3',
        lesson_id: 'les-12-1-1',
        code: 'Dạng 3',
        title_vi: 'Tìm tham số m để hàm số đơn điệu hoặc đạt cực trị',
        title_en: 'Parameter m Conditions for Monotonicity and Extrema',
        order_index: 3,
        sample_count_tn: 2,
        sample_count_ds: 1,
        sample_count_tln: 1,
        sample_count_tl: 1,
      },
      {
        id: 'type-12-1-4',
        lesson_id: 'les-12-1-1',
        code: 'Dạng 4 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tối ưu hoá tốc độ tăng trưởng kinh tế & tốc độ truyền tin',
        title_en: 'Real-world Application: Growth Rate and Information Propagation Optimization',
        order_index: 4,
        sample_count_tn: 1,
        sample_count_ds: 1,
        sample_count_tln: 1,
        sample_count_tl: 1,
      },
    ],
    worked_examples: [
      {
        id: 'we-12-1-1',
        type_id: 'type-12-1-1',
        type_code: 'Dạng 1. Tìm khoảng đơn điệu',
        title_vi: 'Ví dụ 1: Xét tính đơn điệu của hàm số bậc ba',
        title_en: 'Example 1: Monotonicity of a Cubic Polynomial',
        problem_vi: 'Cho hàm số $y = x^3 - 3x^2 - 45x - 3$. Tìm các khoảng đồng biến và nghịch biến của hàm số.',
        problem_en: 'Given $y = x^3 - 3x^2 - 45x - 3$. Find the intervals of increase and decrease.',
        solution_vi: 'TXĐ: $D = \\mathbb{R}$. Đạo hàm: $y\' = 3x^2 - 6x - 45 = 3(x + 3)(x - 5)$. Cho $y\' = 0 \\iff x = -3$ hoặc $x = 5$. Hàm số đồng biến trên $(-\\infty; -3)$ và $(5; +\\infty)$; nghịch biến trên $(-3; 5)$.',
        solution_en: 'Domain $D = \\mathbb{R}$. Derivative $y\' = 3(x + 3)(x - 5)$. Roots: $x = -3, x = 5$. Strictly increasing on $(-\\infty, -3)$ and $(5, +\\infty)$; strictly decreasing on $(-3, 5)$.',
      },
      {
        id: 'we-12-1-4',
        type_id: 'type-12-1-4',
        type_code: 'Dạng 4 (Ứng dụng thực tế). Tốc độ truyền tin tức',
        title_vi: 'Ví dụ 2 (Ứng dụng thực tế): Tốc độ tiếp cận thông tin người dùng',
        title_en: 'Example 2 (Real-world): Information Diffusion Rate',
        problem_vi: 'Số lượng người tiếp cận một thông báo quảng cáo sau $t$ ngày được mô hình hoá bởi $N(t) = -t^3 + 12t^2 + 60t$ (với $0 \\le t \\le 10$). Hãy xác định ngày mà tốc độ lan truyền thông tin $N\'(t)$ đạt mức lớn nhất.',
        problem_en: 'The number of people reaching an announcement after $t$ days is $N(t) = -t^3 + 12t^2 + 60t$ ($0 \\le t \\le 10$). Find the day when the information diffusion rate $N\'(t)$ is maximum.',
        solution_vi: 'Tốc độ lan truyền là $v(t) = N\'(t) = -3t^2 + 24t + 60$. Đạo hàm: $v\'(t) = -6t + 24 = 0 \\iff t = 4$. Do $v\'\'(t) = -6 < 0$ nên $v(t)$ đạt giá trị lớn nhất tại $t = 4$. Vậy sau đúng 4 ngày thì tốc độ lan truyền thông tin đạt cực đại với $v(4) = 108$ người/ngày.',
        solution_en: 'Diffusion rate is $v(t) = N\'(t) = -3t^2 + 24t + 60$. Derivative $v\'(t) = -6t + 24 = 0 \\iff t = 4$. Max rate is at day 4 with 108 people/day.',
      },
    ],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-1-2',
    chapter_id: 'chap-12-1',
    topic_id: 'top-12-1-2',
    title_vi: 'Bài 2. Giá trị lớn nhất và giá trị nhỏ nhất của hàm số',
    title_en: 'Lesson 2. Maximum and Minimum Values of Functions',
    order_index: 2,
    learning_objectives: [
      'Tìm GTLN (Global Max) và GTNN (Global Min) trên đoạn $[a, b]$ và trên khoảng',
      'Ứng dụng đạo hàm giải bài toán tối ưu hoá thực tế: Chi phí thấp nhất, lợi nhuận cao nhất',
    ],
    vocabulary_list: ['Global Maximum', 'Global Minimum', 'Closed Interval', 'Cost Function', 'Revenue Optimization'],
    key_concepts_vi: '• Trên $[a; b]$: Tính $f(a), f(b)$ và các $f(x_i)$ với $x_i \\in (a; b)$ làm $f\'(x_i)=0$. Giá trị lớn nhất là $\\max$, bé nhất là $\\min$.\n• Trên khoảng $(a; b)$: Lập bảng biến thiên để xác định GTLN, GTNN.',
    key_concepts_en: '• On $[a; b]$: Evaluate $f(a), f(b)$ and $f(x_i)$ where $f\'(x_i)=0$. The maximum value is $\\max$, the minimum is $\\min$.\n• On $(a; b)$: Use the variation table to find absolute extrema.',
    formulas: [
      "\\max_{[a, b]} f(x) = \\max\\{f(a), f(b), f(x_1), \\dots\\}",
      "\\min_{[a, b]} f(x) = \\min\\{f(a), f(b), f(x_1), \\dots\\}",
    ],
    types: [
      {
        id: 'type-12-2-1',
        lesson_id: 'les-12-1-2',
        code: 'Dạng 1',
        title_vi: 'Tìm GTLN - GTNN trên một đoạn [a, b]',
        title_en: 'Find Max and Min on a Closed Interval [a, b]',
        order_index: 1,
      },
      {
        id: 'type-12-2-2',
        lesson_id: 'les-12-1-2',
        code: 'Dạng 2',
        title_vi: 'Tìm GTLN - GTNN trên khoảng hoặc tập xác định',
        title_en: 'Find Max and Min on Open Intervals or Domain',
        order_index: 2,
      },
      {
        id: 'type-12-2-3',
        lesson_id: 'les-12-1-2',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tối ưu hoá chi phí sản xuất, doanh thu và diện tích sử dụng',
        title_en: 'Real-world Application: Cost, Revenue and Area Optimization',
        order_index: 3,
      },
    ],
    worked_examples: [
      {
        id: 'we-12-2-3',
        type_id: 'type-12-2-3',
        type_code: 'Dạng 3 (Ứng dụng thực tế). Tối ưu hoá hộp quà',
        title_vi: 'Ví dụ 1 (Ứng dụng thực tế): Cắt góc tôn làm hộp có thể tích lớn nhất',
        title_en: 'Example 1 (Real-world): Box Volume Optimization',
        problem_vi: 'Người ta muốn làm một chiếc hộp hình hộp chữ nhật không nắp từ một tấm tôn hình vuông cạnh $60\\text{ cm}$ bằng cách cắt đi bốn hình vuông bằng nhau ở bốn góc cạnh $x\\text{ cm}$ rồi gập các mép lên. Tìm $x$ để thể tích khối hộp lớn nhất.',
        problem_en: 'A square metal sheet of side $60\\text{ cm}$ has 4 congruent squares of side $x$ cut from its corners to form an open box. Find $x$ to maximize volume.',
        solution_vi: 'Chiều cao hộp là $x$ ($0 < x < 30$), đáy là hình vuông cạnh $60 - 2x$.\nThể tích: $V(x) = x(60 - 2x)^2 = 4x(30 - x)^2 = 4x(x^2 - 60x + 900) = 4(x^3 - 60x^2 + 900x)$.\nĐạo hàm: $V\'(x) = 4(3x^2 - 120x + 900) = 12(x^2 - 40x + 300) = 12(x - 10)(x - 30)$.\nVới $x \\in (0; 30)$, $V\'(x) = 0 \\iff x = 10\\text{ cm}$.\nVậy cắt cạnh $x = 10\\text{ cm}$ cho thể tích cực đại $V(10) = 10 \\cdot 40^2 = 16000\\text{ cm}^3 = 16\\text{ lít}$.',
        solution_en: 'Height is $x$ ($0 < x < 30$), base side is $60 - 2x$. $V(x) = x(60 - 2x)^2$. $V\'(x) = 12(x - 10)(x - 30) = 0 \\iff x = 10\\text{ cm}$. Maximum volume is $16000\\text{ cm}^3$.',
      },
    ],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-1-3',
    chapter_id: 'chap-12-1',
    topic_id: 'top-12-1-3',
    title_vi: 'Bài 3. Đường tiệm cận của đồ thị hàm số',
    title_en: 'Lesson 3. Asymptotes of Function Graphs',
    order_index: 3,
    learning_objectives: [
      'Xác định tiệm cận đứng (Vertical Asymptote), tiệm cận ngang (Horizontal Asymptote)',
      'Xác định tiệm cận xiên (Oblique Asymptote) của đồ thị hàm phân thức',
      'Ứng dụng tiệm cận trong mô hình nồng độ thuốc và chi phí trung bình bão hòa',
    ],
    vocabulary_list: ['Vertical Asymptote', 'Horizontal Asymptote', 'Oblique Asymptote', 'Saturation Level'],
    key_concepts_vi: `• $\\lim_{x \\to x_0^+} f(x) = \\pm\\infty \\implies x = x_0$ là Tiệm cận đứng (TCĐ).\n• $\\lim_{x \\to \\pm\\infty} f(x) = y_0 \\implies y = y_0$ là Tiệm cận ngang (TCN).\n• $\\lim_{x \\to \\pm\\infty} [f(x) - (ax+b)] = 0 \\implies y = ax+b$ là Tiệm cận xiên (TCX).`,
    key_concepts_en: `• $\\lim_{x \\to x_0^+} f(x) = \\pm\\infty \\implies x = x_0$ is Vertical Asymptote.\n• $\\lim_{x \\to \\pm\\infty} f(x) = y_0 \\implies y = y_0$ is Horizontal Asymptote.\n• $\\lim_{x \\to \\pm\\infty} [f(x) - (ax+b)] = 0 \\implies y = ax+b$ is Oblique Asymptote.`,
    formulas: [
      "\\lim_{x \\to x_0^+} f(x) = \\pm\\infty \\implies x = x_0 \\text{ (TCĐ)}",
      "\\lim_{x \\to \\pm\\infty} f(x) = y_0 \\implies y = y_0 \\text{ (TCN)}",
      "y = \\frac{ax^2+bx+c}{px+q} = mx+n + \\frac{r}{px+q} \\implies \\text{TCX: } y = mx + n",
    ],
    types: [
      {
        id: 'type-12-3-1',
        lesson_id: 'les-12-1-3',
        code: 'Dạng 1',
        title_vi: 'Tìm tiệm cận đứng và tiệm cận ngang của hàm phân thức hữu tỉ',
        title_en: 'Find Vertical and Horizontal Asymptotes',
        order_index: 1,
      },
      {
        id: 'type-12-3-2',
        lesson_id: 'les-12-1-3',
        code: 'Dạng 2',
        title_vi: 'Tìm tiệm cận xiên của hàm phân thức bậc 2 / bậc 1',
        title_en: 'Find Oblique Asymptotes of Quadratic-over-Linear Functions',
        order_index: 2,
      },
      {
        id: 'type-12-3-3',
        lesson_id: 'les-12-1-3',
        code: 'Dạng 3',
        title_vi: 'Tìm tham số m để đồ thị có số tiệm cận cho trước',
        title_en: 'Parameter m Conditions for Asymptotes',
        order_index: 3,
      },
      {
        id: 'type-12-3-4',
        lesson_id: 'les-12-1-3',
        code: 'Dạng 4 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Mức bão hoà nồng độ dung dịch và chi phí sản xuất trung bình',
        title_en: 'Real-world Application: Drug Concentration Saturation and Average Cost',
        order_index: 4,
      },
    ],
    worked_examples: [
      {
        id: 'we-12-3-1',
        type_id: 'type-12-3-1',
        type_code: 'Dạng 1. Tiệm cận đứng và ngang',
        title_vi: 'Ví dụ 1: Tìm tiệm cận của hàm số phân thức bậc nhất',
        title_en: 'Example 1: Linear Rational Function Asymptotes',
        problem_vi: 'Tìm tiệm cận đứng và tiệm cận ngang của đồ thị hàm số $y = \\frac{2x - 3}{x + 1}$.',
        problem_en: 'Find the vertical and horizontal asymptotes of $y = \\frac{2x - 3}{x + 1}$.',
        solution_vi: 'TCĐ: $x = -1$ (vì $\\lim_{x \\to -1^+} y = -\\infty$). TCN: $y = 2$ (vì $\\lim_{x \\to \\pm\\infty} y = 2$).',
        solution_en: 'Vertical asymptote $x = -1$; horizontal asymptote $y = 2$.',
      },
    ],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-1-4',
    chapter_id: 'chap-12-1',
    topic_id: 'top-12-1-4',
    title_vi: 'Bài 4. Khảo sát sự biến thiên và vẽ đồ thị của hàm số',
    title_en: 'Lesson 4. Curve Sketching and Graphing Functions',
    order_index: 4,
    learning_objectives: [
      'Nắm vững các bước khảo sát hàm số bậc ba, hàm phân thức $y = \\frac{ax+b}{cx+d}$ và $y = \\frac{ax^2+bx+c}{dx+e}$',
      'Đọc đồ thị, biện luận số nghiệm phương trình theo tham số $m$',
    ],
    vocabulary_list: ['Curve Sketching', 'Inflection Point', 'Symmetry Center', 'Number of Roots'],
    key_concepts_vi: 'Sơ đồ khảo sát: TXĐ $\\to$ Sự biến thiên ($y\', y\'=0$, khoảng đơn điệu, cực trị, tiệm cận) $\\to$ Bảng biến thiên $\\to$ Điểm đặc biệt $\\to$ Vẽ đồ thị.',
    key_concepts_en: 'Graphing: Domain $\\to$ Derivatives, monotonicity, extrema, asymptotes $\\to$ Variation Table $\\to$ Special points $\\to$ Plot curve.',
    formulas: [],
    types: [
      {
        id: 'type-12-4-1',
        lesson_id: 'les-12-1-4',
        code: 'Dạng 1',
        title_vi: 'Khảo sát và vẽ đồ thị hàm số bậc ba $y = ax^3 + bx^2 + cx + d$',
        title_en: 'Graph Cubic Polynomial Functions',
        order_index: 1,
      },
      {
        id: 'type-12-4-2',
        lesson_id: 'les-12-1-4',
        code: 'Dạng 2',
        title_vi: 'Khảo sát và vẽ đồ thị hàm phân thức $y = \\frac{ax+b}{cx+d}$',
        title_en: 'Graph Linear Rational Functions',
        order_index: 2,
      },
      {
        id: 'type-12-4-3',
        lesson_id: 'les-12-1-4',
        code: 'Dạng 3',
        title_vi: 'Khảo sát và vẽ đồ thị hàm phân thức bậc 2 / bậc 1 $y = \\frac{ax^2+bx+c}{px+q}$',
        title_en: 'Graph Quadratic-over-Linear Rational Functions',
        order_index: 3,
      },
      {
        id: 'type-12-4-4',
        lesson_id: 'les-12-1-4',
        code: 'Dạng 4',
        title_vi: 'Biện luận số nghiệm của phương trình bằng phương pháp đồ thị',
        title_en: 'Determine Number of Roots Using Graphical Methods',
        order_index: 4,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-1-5',
    chapter_id: 'chap-12-1',
    topic_id: 'top-12-1-5',
    title_vi: 'Bài 5. Ứng dụng đạo hàm để giải quyết vấn đề thực tiễn',
    title_en: 'Lesson 5. Practical Problem Solving with Derivatives',
    order_index: 5,
    learning_objectives: [
      'Mô hình hoá các bài toán thực tế thành bài toán tìm cực trị hàm số',
      'Giải bài toán tối ưu hoá dung tích bể chứa, doanh thu tối đa, tiết kiệm nguyên vật liệu',
    ],
    vocabulary_list: ['Mathematical Modeling', 'Optimization', 'Profit Maximization', 'Material Minimization'],
    key_concepts_vi: 'Quy trình giải bài toán thực tế: 1) Chọn biến số $x$ và tìm miền xác định thực tế; 2) Thiết lập hàm số mục tiêu $f(x)$; 3) Khảo sát tìm GTLN hoặc GTNN của $f(x)$; 4) Kết luận.',
    key_concepts_en: 'Real-world optimization steps: 1) Choose variable $x$ and practical domain; 2) Build objective function $f(x)$; 3) Find extrema using derivatives; 4) Conclude.',
    formulas: [],
    types: [
      {
        id: 'type-12-5-1',
        lesson_id: 'les-12-1-5',
        code: 'Dạng 1 (Ứng dụng thực tế)',
        title_vi: 'Bài toán tối ưu hoá hình học: Dung tích bể nước, diện tích rào chắn, tiết kiệm tôn',
        title_en: 'Geometric Optimization: Tank Volume, Fenced Area, Metal Sheet Saving',
        order_index: 1,
      },
      {
        id: 'type-12-5-2',
        lesson_id: 'les-12-1-5',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Bài toán kinh tế: Tối ưu lợi nhuận, doanh thu bán hàng, giảm chi phí vận hành',
        title_en: 'Economic Optimization: Profit Maximization, Revenue, Operating Cost',
        order_index: 2,
      },
      {
        id: 'type-12-5-3',
        lesson_id: 'les-12-1-5',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Bài toán vật lý & chuyển động: Thời gian di chuyển ngắn nhất, vận tốc dòng chảy',
        title_en: 'Physics & Kinematics: Shortest Travel Time, Flow Velocity',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 12: CHƯƠNG II - VECTƠ VÀ HỆ TOẠ ĐỘ TRONG KHÔNG GIAN
  // =========================================================================
  {
    id: 'les-12-2-1',
    chapter_id: 'chap-12-2',
    topic_id: 'top-12-2-1',
    title_vi: 'Bài 6. Vectơ trong không gian',
    title_en: 'Lesson 6. Vectors in 3D Space',
    order_index: 1,
    learning_objectives: [
      'Thực hiện các phép toán cộng, trừ, nhân vectơ với một số trong không gian',
      'Hiểu và vận dụng quy tắc hình hộp, ba vectơ đồng phẳng và phân tích vectơ',
    ],
    vocabulary_list: ['Spatial Vector', 'Parallelepiped Rule', 'Coplanar Vectors', 'Force Resultant'],
    key_concepts_vi: '• Quy tắc hình hộp: Với hình hộp $ABCD.A\'B\'C\'D\'$ ta có $\\vec{AC\'} = \\vec{AB} + \\vec{AD} + \\vec{AA\'}$.\n• Ba vectơ $\\vec{a}, \\vec{b}, \\vec{c}$ đồng phẳng khi và chỉ khi tồn tại cặp số $m, n$ sao cho $\\vec{c} = m\\vec{a} + n\\vec{b}$.',
    key_concepts_en: '• Parallelepiped rule: $\\vec{AC\'} = \\vec{AB} + \\vec{AD} + \\vec{AA\'}$.\n• Three vectors are coplanar if $\\vec{c} = m\\vec{a} + n\\vec{b}$.',
    formulas: [
      "\\vec{AC'} = \\vec{AB} + \\vec{AD} + \\vec{AA'}",
      "\\vec{c} = m\\vec{a} + n\\vec{b}",
    ],
    types: [
      {
        id: 'type-12-6-1',
        lesson_id: 'les-12-2-1',
        code: 'Dạng 1',
        title_vi: 'Chứng minh đẳng thức vectơ và tính độ dài vectơ trong không gian',
        title_en: 'Vector Identities and Length in 3D Space',
        order_index: 1,
      },
      {
        id: 'type-12-6-2',
        lesson_id: 'les-12-2-1',
        code: 'Dạng 2',
        title_vi: 'Xét tính đồng phẳng và phân tích một vectơ theo 3 vectơ không đồng phẳng',
        title_en: 'Coplanarity and Vector Decomposition in 3D',
        order_index: 2,
      },
      {
        id: 'type-12-6-3',
        lesson_id: 'les-12-2-1',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Phân tích hợp lực căng dây cáp treo và cân bằng lực giàn không gian',
        title_en: 'Real-world Application: Cable Tension and Space Truss Force Equilibrium',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-2-2',
    chapter_id: 'chap-12-2',
    topic_id: 'top-12-2-2',
    title_vi: 'Bài 7. Hệ toạ độ trong không gian',
    title_en: 'Lesson 7. Coordinate Systems in 3D Space (Oxyz)',
    order_index: 2,
    learning_objectives: [
      'Xác định toạ độ của điểm $M(x; y; z)$ và toạ độ của vectơ $\\vec{u} = (x; y; z)$',
      'Tính toạ độ trung điểm đoạn thẳng, trọng tâm tam giác và tứ diện',
    ],
    vocabulary_list: ['Cartesian Coordinate System', 'Origin', 'Midpoint Formula', 'Centroid', 'GPS Coordinates'],
    key_concepts_vi: '• Điểm $M(x; y; z) \\iff \\vec{OM} = x\\vec{i} + y\\vec{j} + z\\vec{k}$.\n• Toạ độ $\\vec{AB} = (x_B - x_A; y_B - y_A; z_B - z_A)$.\n• Trung điểm $M: x_M = \\frac{x_A+x_B}{2}, y_M = \\frac{y_A+y_B}{2}, z_M = \\frac{z_A+z_B}{2}$.',
    key_concepts_en: '• Point $M(x, y, z) \\iff \\vec{OM} = x\\vec{i} + y\\vec{j} + z\\vec{k}$.\n• Vector $\\vec{AB} = (x_B - x_A, y_B - y_A, z_B - z_A)$.\n• Midpoint $M = \\frac{A+B}{2}$; Centroid $G = \\frac{A+B+C}{3}$.',
    formulas: [
      "\\vec{OM} = x\\vec{i} + y\\vec{j} + z\\vec{k}",
      "\\vec{AB} = (x_B - x_A; y_B - y_A; z_B - z_A)",
      "M = \\left(\\frac{x_A+x_B}{2}; \\frac{y_A+y_B}{2}; \\frac{z_A+z_B}{2}\\right)",
    ],
    types: [
      {
        id: 'type-12-7-1',
        lesson_id: 'les-12-2-2',
        code: 'Dạng 1',
        title_vi: 'Tìm toạ độ của điểm và vectơ trong không gian Oxyz',
        title_en: 'Find Point and Vector Coordinates in 3D Space',
        order_index: 1,
      },
      {
        id: 'type-12-7-2',
        lesson_id: 'les-12-2-2',
        code: 'Dạng 2',
        title_vi: 'Tìm toạ độ điểm thoả mãn điều kiện hình học (hình bình hành, trung điểm, trọng tâm)',
        title_en: 'Geometric Point Coordinates (Parallelogram, Centroid)',
        order_index: 2,
      },
      {
        id: 'type-12-7-3',
        lesson_id: 'les-12-2-2',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Định vị toạ độ 3D máy bay, vệ tinh nhân tạo và trạm radar kiểm soát',
        title_en: 'Real-world Application: Aircraft 3D GPS Positioning and Radar Tracking Station',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-2-3',
    chapter_id: 'chap-12-2',
    topic_id: 'top-12-2-3',
    title_vi: 'Bài 8. Biểu thức toạ độ của các phép toán vectơ',
    title_en: 'Lesson 8. Coordinate Expressions of Vector Operations',
    order_index: 3,
    learning_objectives: [
      'Tính tích vô hướng, độ dài vectơ và góc giữa hai vectơ trong không gian',
      'Tính tích có hướng của 2 vectơ và ứng dụng tính diện tích tam giác, thể tích tứ diện',
    ],
    vocabulary_list: ['Dot Product', 'Cross Product', 'Angle between Vectors', 'Solar Panel Tilt'],
    key_concepts_vi: '• Tích vô hướng: $\\vec{u} \\cdot \\vec{v} = x_1x_2 + y_1y_2 + z_1z_2$.\n• Độ dài: $|\\vec{u}| = \\sqrt{x^2 + y^2 + z^2}$.\n• Côsin góc: $\\cos(\\vec{u}, \\vec{v}) = \\frac{\\vec{u}\\cdot\\vec{v}}{|\\vec{u}||\\vec{v}|}$.\n• Tích có hướng: $[\\vec{u}, \\vec{v}] = (y_1z_2 - z_1y_2; z_1x_2 - x_1z_2; x_1y_2 - y_1x_2)$.',
    key_concepts_en: '• Dot product: $\\vec{u} \\cdot \\vec{v} = x_1x_2 + y_1y_2 + z_1z_2$.\n• Length: $|\\vec{u}| = \\sqrt{x^2+y^2+z^2}$.\n• Cross product: $[\\vec{u}, \\vec{v}] = (y_1z_2 - z_1y_2, z_1x_2 - x_1z_2, x_1y_2 - y_1x_2)$.',
    formulas: [
      "\\vec{u} \\cdot \\vec{v} = x_1x_2 + y_1y_2 + z_1z_2",
      "|\\vec{u}| = \\sqrt{x^2 + y^2 + z^2}",
      "\\cos(\\vec{u}, \\vec{v}) = \\frac{x_1x_2 + y_1y_2 + z_1z_2}{\\sqrt{x_1^2+y_1^2+z_1^2}\\sqrt{x_2^2+y_2^2+z_2^2}}",
    ],
    types: [
      {
        id: 'type-12-8-1',
        lesson_id: 'les-12-2-3',
        code: 'Dạng 1',
        title_vi: 'Tính tích vô hướng, độ dài vectơ và góc giữa hai vectơ',
        title_en: 'Dot Product, Length, and Angle Calculation',
        order_index: 1,
      },
      {
        id: 'type-12-8-2',
        lesson_id: 'les-12-2-3',
        code: 'Dạng 2',
        title_vi: 'Tích có hướng và ứng dụng tính diện tích tam giác, thể tích khối chóp',
        title_en: 'Cross Product and Area, Volume Applications',
        order_index: 2,
      },
      {
        id: 'type-12-8-3',
        lesson_id: 'les-12-2-3',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tính góc chiếu tia nắng mặt trời và hiệu suất tấm pin năng lượng',
        title_en: 'Real-world Application: Solar Panel Angle of Incidence and Solar Radiation Efficiency',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 12: CHƯƠNG III - THỐNG KÊ MẪU SỐ LIỆU GHÉP NHÓM
  // =========================================================================
  {
    id: 'les-12-3-1',
    chapter_id: 'chap-12-3',
    topic_id: 'top-12-3-1',
    title_vi: 'Bài 9. Khoảng biến thiên và khoảng tứ phân vị của mẫu số liệu ghép nhóm',
    title_en: 'Lesson 9. Range and Interquartile Range for Grouped Data',
    order_index: 1,
    learning_objectives: [
      'Tính khoảng biến thiên $R$ của mẫu số liệu ghép nhóm',
      'Tính tứ phân vị $Q_1, Q_2, Q_3$ và khoảng tứ phân vị $\\Delta_Q = Q_3 - Q_1$',
    ],
    vocabulary_list: ['Range', 'Interquartile Range', 'Quartiles', 'Grouped Frequency Table'],
    key_concepts_vi: '• Khoảng biến thiên: $R = a_{k+1} - a_1$ (đầu mút phải nhóm cuối trừ đầu mút trái nhóm đầu).\n• Khoảng tứ phân vị: $\\Delta_Q = Q_3 - Q_1$ dùng để đo độ phân tán của 50% số liệu chính giữa.',
    key_concepts_en: '• Range: $R = a_{k+1} - a_1$.\n• Interquartile range: $\\Delta_Q = Q_3 - Q_1$ measures spread of central 50% data.',
    formulas: [
      "R = a_{k+1} - a_1",
      "\\Delta_Q = Q_3 - Q_1",
      "Q_p = u_m + \\frac{\\frac{pn}{4} - C}{n_m}(u_{m+1} - u_m)",
    ],
    types: [
      {
        id: 'type-12-9-1',
        lesson_id: 'les-12-3-1',
        code: 'Dạng 1',
        title_vi: 'Tính khoảng biến thiên và khoảng tứ phân vị từ bảng ghép nhóm',
        title_en: 'Compute Range and IQR from Grouped Frequency Tables',
        order_index: 1,
      },
      {
        id: 'type-12-9-2',
        lesson_id: 'les-12-3-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Đánh giá sự phân tán điểm thi, độ chênh lệch thu nhập người lao động',
        title_en: 'Real-world Application: Income Inequality and Test Score Dispersion Analysis',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-3-2',
    chapter_id: 'chap-12-3',
    topic_id: 'top-12-3-2',
    title_vi: 'Bài 10. Phương sai và độ lệch chuẩn của mẫu số liệu ghép nhóm',
    title_en: 'Lesson 10. Variance and Standard Deviation for Grouped Data',
    order_index: 2,
    learning_objectives: [
      'Tính số trung bình $\\bar{x}$, phương sai $s^2$ và độ lệch chuẩn $s$',
      'So sánh độ ổn định và mức độ rủi ro giữa hai tập mẫu số liệu',
    ],
    vocabulary_list: ['Sample Mean', 'Variance', 'Standard Deviation', 'Volatility', 'Risk Assessment'],
    key_concepts_vi: '• Số trung bình: $\\bar{x} = \\frac{1}{n}\\sum n_i c_i$ ($c_i$ là giá trị đại diện nhóm).\n• Phương sai: $s^2 = \\frac{1}{n}\\sum n_i c_i^2 - \\bar{x}^2$.\n• Độ lệch chuẩn: $s = \\sqrt{s^2}$. Độ lệch chuẩn càng nhỏ thì dữ liệu càng đồng đều.',
    key_concepts_en: '• Mean: $\\bar{x} = \\frac{1}{n}\\sum n_i c_i$.\n• Variance: $s^2 = \\frac{1}{n}\\sum n_i c_i^2 - \\bar{x}^2$.\n• Standard deviation: $s = \\sqrt{s^2}$. Smaller standard deviation indicates higher consistency.',
    formulas: [
      "\\bar{x} = \\frac{1}{n}\\sum_{i=1}^k n_i c_i",
      "s^2 = \\frac{1}{n}\\sum_{i=1}^k n_i c_i^2 - \\bar{x}^2",
      "s = \\sqrt{s^2}",
    ],
    types: [
      {
        id: 'type-12-10-1',
        lesson_id: 'les-12-3-2',
        code: 'Dạng 1',
        title_vi: 'Tính phương sai và độ lệch chuẩn của mẫu số liệu ghép nhóm',
        title_en: 'Calculate Variance and Standard Deviation',
        order_index: 1,
      },
      {
        id: 'type-12-10-2',
        lesson_id: 'les-12-3-2',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Đánh giá độ rủi ro cổ phiếu tài chính và độ đồng đều năng suất cây trồng',
        title_en: 'Real-world Application: Stock Price Volatility and Agricultural Yield Consistency',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 12: CHƯƠNG IV - NGUYÊN HÀM VÀ TÍCH PHÂN
  // =========================================================================
  {
    id: 'les-12-4-1',
    chapter_id: 'chap-12-4',
    topic_id: 'top-12-4-1',
    title_vi: 'Bài 11. Nguyên hàm',
    title_en: 'Lesson 11. Antiderivatives',
    order_index: 1,
    learning_objectives: [
      'Nắm vững bảng nguyên hàm của các hàm số sơ cấp cơ bản',
      'Thành thạo phương pháp đổi biến số và phương pháp nguyên hàm từng phần',
    ],
    vocabulary_list: ['Antiderivative', 'Indefinite Integral', 'Integration by Substitution', 'Integration by Parts'],
    key_concepts_vi: '• $F(x)$ là nguyên hàm của $f(x)$ nếu $F\'(x) = f(x)$.\n• Từng phần: $\\int u\\,dv = uv - \\int v\\,du$.\n• Thứ tự ưu tiên đặt $u$: "Nhất lô, nhì đa, tam lượng, tứ mũ".',
    key_concepts_en: '• $F\'(x) = f(x) \\implies \\int f(x)dx = F(x) + C$.\n• By parts: $\\int u\\,dv = uv - \\int v\\,du$.\n• Priority for $u$: Logarithmic, Polynomial, Trigonometric, Exponential.',
    formulas: [
      "\\int x^\\alpha dx = \\frac{x^{\\alpha+1}}{\\alpha+1} + C \\quad (\\alpha \\neq -1)",
      "\\int \\frac{1}{x} dx = \\ln|x| + C",
      "\\int e^x dx = e^x + C; \\quad \\int a^x dx = \\frac{a^x}{\\ln a} + C",
      "\\int u\\,dv = uv - \\int v\\,du",
    ],
    types: [
      {
        id: 'type-12-11-1',
        lesson_id: 'les-12-4-1',
        code: 'Dạng 1',
        title_vi: 'Tìm nguyên hàm bằng bảng nguyên hàm cơ bản và phân tích',
        title_en: 'Find Antiderivatives Using Standard Formulas',
        order_index: 1,
      },
      {
        id: 'type-12-11-2',
        lesson_id: 'les-12-4-1',
        code: 'Dạng 2',
        title_vi: 'Tìm nguyên hàm bằng phương pháp đổi biến số',
        title_en: 'Integration by Substitution',
        order_index: 2,
      },
      {
        id: 'type-12-11-3',
        lesson_id: 'les-12-4-1',
        code: 'Dạng 3',
        title_vi: 'Tìm nguyên hàm bằng phương pháp từng phần',
        title_en: 'Integration by Parts',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-4-2',
    chapter_id: 'chap-12-4',
    topic_id: 'top-12-4-2',
    title_vi: 'Bài 12. Tích phân',
    title_en: 'Lesson 12. Definite Integrals',
    order_index: 2,
    learning_objectives: [
      'Hiểu định nghĩa tích phân Newton - Leibniz: $\\int_a^b f(x)dx = F(b) - F(a)$',
      'Vận dụng tích phân giải bài toán vật lý: Quãng đường chuyển động và công sinh ra',
    ],
    vocabulary_list: ['Definite Integral', 'Fundamental Theorem of Calculus', 'Velocity Integral', 'Total Distance'],
    key_concepts_vi: '• Định nghĩa: $\\int_a^b f(x)dx = F(b) - F(a)$.\n• Tính chất: $\\int_a^b f(x)dx = \\int_a^c f(x)dx + \\int_c^b f(x)dx$.\n• Ứng dụng vật lý: Quãng đường $s = \\int_{t_1}^{t_2} v(t)dt$.',
    key_concepts_en: '• Definition: $\\int_a^b f(x)dx = F(b) - F(a)$.\n• Additivity: $\\int_a^b = \\int_a^c + \\int_c^b$.\n• Physics: Distance traveled is $s = \\int_{t_1}^{t_2} v(t)dt$.',
    formulas: [
      "\\int_a^b f(x)dx = F(b) - F(a) = \\left. F(x) \\right|_a^b",
      "s(t) = \\int_{t_1}^{t_2} v(t)dt",
    ],
    types: [
      {
        id: 'type-12-12-1',
        lesson_id: 'les-12-4-2',
        code: 'Dạng 1',
        title_vi: 'Tính tích phân bằng phương pháp đổi biến số và từng phần',
        title_en: 'Evaluate Definite Integrals with Substitution and Parts',
        order_index: 1,
      },
      {
        id: 'type-12-12-2',
        lesson_id: 'les-12-4-2',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tính quãng đường ô tô phanh gấp, lượng điện năng tiêu thụ',
        title_en: 'Real-world Application: Braking Distance and Energy Consumption Integrals',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-4-3',
    chapter_id: 'chap-12-4',
    topic_id: 'top-12-4-3',
    title_vi: 'Bài 13. Ứng dụng hình học của tích phân',
    title_en: 'Lesson 13. Geometric Applications of Integrals',
    order_index: 3,
    learning_objectives: [
      'Tính diện tích hình phẳng giới hạn bởi các đường cong: $S = \\int_a^b |f(x) - g(x)|dx$',
      'Tính thể tích khối tròn xoay: $V = \\pi \\int_a^b [f(x)]^2 dx$',
      'Tính diện tích mảnh đất thực tế và thể tích thùng phuy, bồn chứa cong',
    ],
    vocabulary_list: ['Area of Plane Region', 'Volume of Solid of Revolution', 'Cross-section Area', 'Barrel Volume'],
    key_concepts_vi: '• Diện tích hình phẳng: $S = \\int_a^b |f(x) - g(x)|dx$.\n• Thể tích tròn xoay quanh trục $Ox$: $V = \\pi \\int_a^b f^2(x)dx$.\n• Thể tích vật thể có diện tích thiết diện $S(x)$: $V = \\int_a^b S(x)dx$.',
    key_concepts_en: '• Area: $S = \\int_a^b |f(x) - g(x)|dx$.\n• Solid of revolution around $Ox$: $V = \\pi \\int_a^b f^2(x)dx$.\n• Solid with cross-section area $S(x)$: $V = \\int_a^b S(x)dx$.',
    formulas: [
      "S = \\int_a^b |f(x) - g(x)| dx",
      "V_{Ox} = \\pi \\int_a^b [f(x)]^2 dx",
      "V = \\int_a^b S(x) dx",
    ],
    types: [
      {
        id: 'type-12-13-1',
        lesson_id: 'les-12-4-3',
        code: 'Dạng 1',
        title_vi: 'Tính diện tích hình phẳng giới hạn bởi các đường cong',
        title_en: 'Calculate Area of Regions Bounded by Curves',
        order_index: 1,
      },
      {
        id: 'type-12-13-2',
        lesson_id: 'les-12-4-3',
        code: 'Dạng 2',
        title_vi: 'Tính thể tích khối tròn xoay khi quay quanh trục toạ độ',
        title_en: 'Calculate Volume of Solids of Revolution',
        order_index: 2,
      },
      {
        id: 'type-12-13-3',
        lesson_id: 'les-12-4-3',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tính diện tích sân vườn viền parabol, thể tích bồn nước hình elipxoit',
        title_en: 'Real-world Application: Parabolic Garden Area and Ellipsoidal Tank Volume',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 12: CHƯƠNG V - PHƯƠNG PHÁP TOẠ ĐỘ TRONG KHÔNG GIAN (OXYZ)
  // =========================================================================
  {
    id: 'les-12-5-1',
    chapter_id: 'chap-12-5',
    topic_id: 'top-12-5-1',
    title_vi: 'Bài 14. Phương trình mặt phẳng',
    title_en: 'Lesson 14. Equations of Planes in Space',
    order_index: 1,
    learning_objectives: [
      'Lập phương trình tổng quát của mặt phẳng: $Ax + By + Cz + D = 0$',
      'Tính khoảng cách từ một điểm đến mặt phẳng: $d(M, (P)) = \\frac{|Ax_0+By_0+Cz_0+D|}{\\sqrt{A^2+B^2+C^2}}$',
    ],
    vocabulary_list: ['Plane Equation', 'Normal Vector', 'Distance to Plane', 'Parallel Planes'],
    key_concepts_vi: '• Mặt phẳng đi qua $M_0(x_0; y_0; z_0)$ có VTPT $\\vec{n}=(A; B; C)$ có dạng: $A(x-x_0) + B(y-y_0) + C(z-z_0) = 0$.\n• Phương trình mặt phẳng theo đoạn chắn: $\\frac{x}{a} + \\frac{y}{b} + \\frac{z}{c} = 1$.',
    key_concepts_en: '• Plane passing through $M_0(x_0, y_0, z_0)$ with normal $\\vec{n}=(A, B, C)$: $A(x-x_0) + B(y-y_0) + C(z-z_0) = 0$.\n• Intercept form: $\\frac{x}{a} + \\frac{y}{b} + \\frac{z}{c} = 1$.',
    formulas: [
      "A(x - x_0) + B(y - y_0) + C(z - z_0) = 0",
      "d(M_0, (P)) = \\frac{|Ax_0 + By_0 + Cz_0 + D|}{\\sqrt{A^2 + B^2 + C^2}}",
    ],
    types: [
      {
        id: 'type-12-14-1',
        lesson_id: 'les-12-5-1',
        code: 'Dạng 1',
        title_vi: 'Viết phương trình mặt phẳng qua 1 điểm và có VTPT / qua 3 điểm',
        title_en: 'Write Plane Equations from Point and Normal Vector / 3 Points',
        order_index: 1,
      },
      {
        id: 'type-12-14-2',
        lesson_id: 'les-12-5-1',
        code: 'Dạng 2',
        title_vi: 'Tính khoảng cách từ điểm đến mặt phẳng và góc giữa 2 mặt phẳng',
        title_en: 'Distance from Point to Plane and Dihedral Angle',
        order_index: 2,
      },
      {
        id: 'type-12-14-3',
        lesson_id: 'les-12-5-1',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Thiết kế mặt nghiêng mái dốc nhà kính và góc chiếu đón gió',
        title_en: 'Real-world Application: Greenhouse Roof Pitch Plane and Wind Direction Angle',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-5-2',
    chapter_id: 'chap-12-5',
    topic_id: 'top-12-5-2',
    title_vi: 'Bài 15. Phương trình đường thẳng trong không gian',
    title_en: 'Lesson 15. Equations of Lines in Space',
    order_index: 2,
    learning_objectives: [
      'Viết phương trình tham số và chính tắc của đường thẳng trong không gian',
      'Xét vị trí tương đối giữa hai đường thẳng; tính góc và khoảng cách',
    ],
    vocabulary_list: ['Parametric Equations', 'Symmetric Equations', 'Direction Vector', 'Skew Lines', 'Flight Path'],
    key_concepts_vi: '• Đường thẳng qua $M_0(x_0; y_0; z_0)$ có VTCP $\\vec{u}=(a; b; c)$: $\\begin{cases} x = x_0 + at \\\\ y = y_0 + bt \\\\ z = z_0 + ct \\end{cases}$.\n• Phương trình chính tắc: $\\frac{x - x_0}{a} = \\frac{y - y_0}{b} = \\frac{z - z_0}{c}$.',
    key_concepts_en: '• Parametric form: $x = x_0 + at, y = y_0 + bt, z = z_0 + ct$.\n• Symmetric form: $\\frac{x - x_0}{a} = \\frac{y - y_0}{b} = \\frac{z - z_0}{c}$.',
    formulas: [
      "\\begin{cases} x = x_0 + at \\\\ y = y_0 + bt \\\\ z = z_0 + ct \\end{cases}",
      "\\frac{x - x_0}{a} = \\frac{y - y_0}{b} = \\frac{z - z_0}{c}",
    ],
    types: [
      {
        id: 'type-12-15-1',
        lesson_id: 'les-12-5-2',
        code: 'Dạng 1',
        title_vi: 'Viết phương trình tham số và chính tắc của đường thẳng',
        title_en: 'Write Parametric and Symmetric Line Equations',
        order_index: 1,
      },
      {
        id: 'type-12-15-2',
        lesson_id: 'les-12-5-2',
        code: 'Dạng 2',
        title_vi: 'Vị trí tương đối giữa hai đường thẳng; khoảng cách giữa 2 đường thẳng chéo nhau',
        title_en: 'Relative Positions and Distance between Skew Lines',
        order_index: 2,
      },
      {
        id: 'type-12-15-3',
        lesson_id: 'les-12-5-2',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Khoảng cách an toàn tối thiểu giữa hai đường bay của máy bay',
        title_en: 'Real-world Application: Minimum Safe Distance between Flight Trajectories',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-5-3',
    chapter_id: 'chap-12-5',
    topic_id: 'top-12-5-3',
    title_vi: 'Bài 16. Phương trình mặt cầu',
    title_en: 'Lesson 16. Equations of Spheres in Space',
    order_index: 3,
    learning_objectives: [
      'Viết phương trình mặt cầu tâm $I(a; b; c)$, bán kính $R$: $(x-a)^2 + (y-b)^2 + (z-c)^2 = R^2$',
      'Xét vị trí tương đối giữa mặt cầu và mặt phẳng/đường thẳng',
    ],
    vocabulary_list: ['Sphere Equation', 'Center', 'Radius', 'Tangent Plane', 'Radar Coverage Sphere'],
    key_concepts_vi: '• Mặt cầu tâm $I(a; b; c)$, bán kính $R$: $(x - a)^2 + (y - b)^2 + (z - c)^2 = R^2$.\n• Dạng khai triển: $x^2 + y^2 + z^2 - 2ax - 2by - 2cz + d = 0$ với $R = \\sqrt{a^2 + b^2 + c^2 - d} > 0$.',
    key_concepts_en: '• Standard sphere: $(x - a)^2 + (y - b)^2 + (z - c)^2 = R^2$.\n• General form: $x^2 + y^2 + z^2 - 2ax - 2by - 2cz + d = 0$ with $R = \\sqrt{a^2+b^2+c^2-d}$.',
    formulas: [
      "(x - a)^2 + (y - b)^2 + (z - c)^2 = R^2",
      "R = \\sqrt{a^2 + b^2 + c^2 - d}",
    ],
    types: [
      {
        id: 'type-12-16-1',
        lesson_id: 'les-12-5-3',
        code: 'Dạng 1',
        title_vi: 'Tìm tâm, bán kính và lập phương trình mặt cầu',
        title_en: 'Find Center, Radius, and Write Sphere Equations',
        order_index: 1,
      },
      {
        id: 'type-12-16-2',
        lesson_id: 'les-12-5-3',
        code: 'Dạng 2',
        title_vi: 'Bài toán tương giao giữa mặt cầu với mặt phẳng và đường thẳng',
        title_en: 'Intersection of Sphere with Planes and Lines',
        order_index: 2,
      },
      {
        id: 'type-12-16-3',
        lesson_id: 'les-12-5-3',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Xác định không gian quét sóng radar và vùng phủ sóng trạm vệ tinh',
        title_en: 'Real-world Application: 3D Radar Scanning Range and Satellite Transmission Sphere',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 12: CHƯƠNG VI - XÁC SUẤT CÓ ĐIỀU KIỆN
  // =========================================================================
  {
    id: 'les-12-6-1',
    chapter_id: 'chap-12-6',
    topic_id: 'top-12-6-1',
    title_vi: 'Bài 17. Xác suất có điều kiện',
    title_en: 'Lesson 17. Conditional Probability',
    order_index: 1,
    learning_objectives: [
      'Hiểu và tính xác suất có điều kiện $P(A|B) = \\frac{P(AB)}{P(B)}$',
      'Vận dụng công thức nhân xác suất $P(AB) = P(B) \\cdot P(A|B)$',
    ],
    vocabulary_list: ['Conditional Probability', 'Multiplication Rule', 'Tree Diagram', 'Quality Control'],
    key_concepts_vi: '• Xác suất của biến cố $A$ khi biết $B$ đã xảy ra: $P(A|B) = \\frac{P(AB)}{P(B)}$ ($P(B) > 0$).\n• Công thức nhân xác suất: $P(AB) = P(A) \\cdot P(B|A) = P(B) \\cdot P(A|B)$.',
    key_concepts_en: '• Conditional probability: $P(A|B) = \\frac{P(AB)}{P(B)}$ ($P(B) > 0$).\n• Multiplication rule: $P(AB) = P(B) \\cdot P(A|B)$.',
    formulas: [
      "P(A|B) = \\frac{P(A \\cap B)}{P(B)}",
      "P(A \\cap B) = P(B) \\cdot P(A|B)",
    ],
    types: [
      {
        id: 'type-12-17-1',
        lesson_id: 'les-12-6-1',
        code: 'Dạng 1',
        title_vi: 'Tính xác suất có điều kiện từ bảng số liệu hoặc định nghĩa',
        title_en: 'Compute Conditional Probability from Frequency Tables',
        order_index: 1,
      },
      {
        id: 'type-12-17-2',
        lesson_id: 'les-12-6-1',
        code: 'Dạng 2',
        title_vi: 'Áp dụng công thức nhân xác suất và vẽ sơ đồ hình cây',
        title_en: 'Multiplication Rule and Tree Diagrams',
        order_index: 2,
      },
      {
        id: 'type-12-17-3',
        lesson_id: 'les-12-6-1',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Kiểm định tỷ lệ phế phẩm dây chuyền công nghiệp',
        title_en: 'Real-world Application: Industrial Manufacturing Defect Rate Testing',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-12-6-2',
    chapter_id: 'chap-12-6',
    topic_id: 'top-12-6-2',
    title_vi: 'Bài 18. Công thức xác suất toàn phần và công thức Bayes',
    title_en: 'Lesson 18. Law of Total Probability and Bayes Theorem',
    order_index: 2,
    learning_objectives: [
      'Nắm vững công thức xác suất toàn phần: $P(A) = \\sum P(B_i)P(A|B_i)$',
      'Vận dụng công thức Bayes tính xác suất hậu nghiệm trong y khoa và xử lý dữ liệu',
    ],
    vocabulary_list: ['Law of Total Probability', 'Bayes Theorem', 'Prior Probability', 'Posterior Probability', 'Medical Diagnosis'],
    key_concepts_vi: '• Xác suất toàn phần: $P(A) = P(B)P(A|B) + P(\\bar{B})P(A|\\bar{B})$.\n• Công thức Bayes: $P(B|A) = \\frac{P(B)P(A|B)}{P(A)} = \\frac{P(B)P(A|B)}{P(B)P(A|B) + P(\\bar{B})P(A|\\bar{B})}$.',
    key_concepts_en: '• Law of Total Probability: $P(A) = P(B)P(A|B) + P(\\bar{B})P(A|\\bar{B})$.\n• Bayes Theorem: $P(B|A) = \\frac{P(B)P(A|B)}{P(A)}$.',
    formulas: [
      "P(A) = \\sum_{i=1}^n P(B_i)P(A|B_i)",
      "P(B_k|A) = \\frac{P(B_k)P(A|B_k)}{\\sum_{i=1}^n P(B_i)P(A|B_i)}",
    ],
    types: [
      {
        id: 'type-12-18-1',
        lesson_id: 'les-12-6-2',
        code: 'Dạng 1',
        title_vi: 'Tính xác suất biến cố bằng công thức xác suất toàn phần',
        title_en: 'Law of Total Probability Calculations',
        order_index: 1,
      },
      {
        id: 'type-12-18-2',
        lesson_id: 'les-12-6-2',
        code: 'Dạng 2',
        title_vi: 'Tính xác suất hậu nghiệm bằng công thức Bayes',
        title_en: 'Posterior Probability using Bayes Formula',
        order_index: 2,
      },
      {
        id: 'type-12-18-3',
        lesson_id: 'les-12-6-2',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Độ chính xác của xét nghiệm chẩn đoán y tế (dương tính thật / giả)',
        title_en: 'Real-world Application: Medical Diagnostic Test Accuracy (True/False Positives)',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 11: CHƯƠNG I - HÀM SỐ LƯỢNG GIÁC & PHƯƠNG TRÌNH LƯỢNG GIÁC
  // =========================================================================
  {
    id: 'les-11-1-1',
    chapter_id: 'chap-11-1',
    topic_id: 'top-11-1-1',
    title_vi: 'Bài 1. Giá trị lượng giác của góc lượng giác',
    title_en: 'Lesson 1. Trigonometric Values of Angles',
    order_index: 1,
    learning_objectives: [
      'Hiểu góc lượng giác, đơn vị radian và các hệ thức lượng giác cơ bản',
    ],
    vocabulary_list: ['Trigonometric Values', 'Radian', 'Unit Circle', 'Sine', 'Cosine'],
    key_concepts_vi: '• Đường tròn lượng giác tâm $O$, $R=1$.\n• $\\sin^2\\alpha + \\cos^2\\alpha = 1$, $1 + \\tan^2\\alpha = \\frac{1}{\\cos^2\\alpha}$.',
    key_concepts_en: '• Unit circle with $R=1$.\n• $\\sin^2\\alpha + \\cos^2\\alpha = 1$, $1 + \\tan^2\\alpha = \\frac{1}{\\cos^2\\alpha}$.',
    formulas: [
      "\\sin^2\\alpha + \\cos^2\\alpha = 1",
      "1 + \\tan^2\\alpha = \\frac{1}{\\cos^2\\alpha}",
    ],
    types: [
      {
        id: 'type-11-1-1',
        lesson_id: 'les-11-1-1',
        code: 'Dạng 1',
        title_vi: 'Tính giá trị lượng giác của một góc khi biết một giá trị',
        title_en: 'Calculate Trigonometric Values Given One Value',
        order_index: 1,
      },
      {
        id: 'type-11-1-2',
        lesson_id: 'les-11-1-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tính góc quay bánh xe đu quay và góc nâng mặt trời',
        title_en: 'Real-world Application: Ferris Wheel Angular Rotation and Solar Elevation Angle',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-1-2',
    chapter_id: 'chap-11-1',
    topic_id: 'top-11-1-2',
    title_vi: 'Bài 2. Công thức lượng giác',
    title_en: 'Lesson 2. Trigonometric Formulas',
    order_index: 2,
    learning_objectives: [
      'Nắm vững công thức cộng, nhân đôi, biến đổi tích thành tổng và tổng thành tích',
    ],
    vocabulary_list: ['Addition Formulas', 'Double Angle Formulas', 'Product-to-Sum Formulas'],
    key_concepts_vi: '• Cộng: $\\sin(a \\pm b) = \\sin a\\cos b \\pm \\cos a\\sin b$, $\\cos(a \\pm b) = \\cos a\\cos b \\mp \\sin a\\sin b$.\n• Nhân đôi: $\\sin 2a = 2\\sin a\\cos a$, $\\cos 2a = \\cos^2 a - \\sin^2 a$.',
    key_concepts_en: '• Addition: $\\sin(a \\pm b) = \\sin a\\cos b \\pm \\cos a\\sin b$.\n• Double angle: $\\sin 2a = 2\\sin a\\cos a$, $\\cos 2a = \\cos^2 a - \\sin^2 a$.',
    formulas: [
      "\\sin(a + b) = \\sin a \\cos b + \\cos a \\sin b",
      "\\sin 2a = 2\\sin a \\cos a",
      "\\cos 2a = 2\\cos^2 a - 1",
    ],
    types: [
      {
        id: 'type-11-2-1',
        lesson_id: 'les-11-1-2',
        code: 'Dạng 1',
        title_vi: 'Rút gọn và tính giá trị biểu thức bằng công thức cộng, nhân đôi',
        title_en: 'Simplify Trigonometric Expressions',
        order_index: 1,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-1-3',
    chapter_id: 'chap-11-1',
    topic_id: 'top-11-1-3',
    title_vi: 'Bài 3. Hàm số lượng giác',
    title_en: 'Lesson 3. Trigonometric Functions',
    order_index: 3,
    learning_objectives: [
      'Tìm tập xác định, chu kỳ và GTLN-GTNN của các hàm số $y = \\sin x, y = \\cos x, y = \\tan x$',
      'Ứng dụng chu kỳ tuần hoàn mô hình hoá sóng biển và nhịp thở sinh học',
    ],
    vocabulary_list: ['Periodicity', 'Amplitude', 'Domain', 'Harmonic Wave', 'Tidal Fluctuation'],
    key_concepts_vi: '• Hàm $y = \\sin x$ và $y = \\cos x$ tuần hoàn với chu kỳ $T = 2\\pi$.\n• Hàm $y = \\tan x$ và $y = \\cot x$ tuần hoàn với chu kỳ $T = \\pi$.',
    key_concepts_en: '• $y = \\sin x, y = \\cos x$ are periodic with period $T = 2\\pi$.\n• $y = \\tan x, y = \\cot x$ are periodic with period $T = \\pi$.',
    formulas: [
      "T_{\\sin, \\cos} = 2\\pi; \\quad T_{\\tan, \\cot} = \\pi",
    ],
    types: [
      {
        id: 'type-11-3-1',
        lesson_id: 'les-11-1-3',
        code: 'Dạng 1',
        title_vi: 'Tìm tập xác định, tính chẵn lẻ và chu kỳ của hàm số lượng giác',
        title_en: 'Domain, Parity, and Period of Trig Functions',
        order_index: 1,
      },
      {
        id: 'type-11-3-2',
        lesson_id: 'les-11-1-3',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Dao động điều hoà con lắc đơn, mực nước thuỷ triều lên xuống',
        title_en: 'Real-world Application: Simple Harmonic Motion and Tidal Wave Height Fluctuation',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-1-4',
    chapter_id: 'chap-11-1',
    topic_id: 'top-11-1-4',
    title_vi: 'Bài 4. Phương trình lượng giác cơ bản',
    title_en: 'Lesson 4. Basic Trigonometric Equations',
    order_index: 4,
    learning_objectives: [
      'Giải thành thạo các phương trình $\\sin x = m, \\cos x = m, \\tan x = m, \\cot x = m$',
    ],
    vocabulary_list: ['Trigonometric Equation', 'Principal Root', 'General Solution'],
    key_concepts_vi: '• $\\sin x = \\sin \\alpha \\iff x = \\alpha + k2\\pi$ hoặc $x = \\pi - \\alpha + k2\\pi$.\n• $\\cos x = \\cos \\alpha \\iff x = \\pm \\alpha + k2\\pi$.\n• $\\tan x = \\tan \\alpha \\iff x = \\alpha + k\\pi$.',
    key_concepts_en: '• $\\sin x = \\sin \\alpha \\iff x = \\alpha + k2\\pi \\lor x = \\pi - \\alpha + k2\\pi$.\n• $\\cos x = \\cos \\alpha \\iff x = \\pm \\alpha + k2\\pi$.\n• $\\tan x = \\tan \\alpha \\iff x = \\alpha + k\\pi$.',
    formulas: [
      "\\sin x = \\sin \\alpha \\iff \\left[\\begin{array}{l} x = \\alpha + k2\\pi \\\\ x = \\pi - \\alpha + k2\\pi \\end{array}\\right.",
      "\\cos x = \\cos \\alpha \\iff x = \\pm \\alpha + k2\\pi",
    ],
    types: [
      {
        id: 'type-11-4-1',
        lesson_id: 'les-11-1-4',
        code: 'Dạng 1',
        title_vi: 'Giải phương trình lượng giác cơ bản và phương trình đưa về dạng cơ bản',
        title_en: 'Solve Basic Trigonometric Equations',
        order_index: 1,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 11: CHƯƠNG II - DÃY SỐ, CẤP SỐ CỘNG VÀ CẤP SỐ NHÂN
  // =========================================================================
  {
    id: 'les-11-2-1',
    chapter_id: 'chap-11-2',
    topic_id: 'top-11-2-1',
    title_vi: 'Bài 5. Dãy số',
    title_en: 'Lesson 5. Numerical Sequences',
    order_index: 1,
    learning_objectives: ['Xét tính tăng, giảm và tính bị chặn của dãy số'],
    vocabulary_list: ['Sequence', 'Increasing Sequence', 'Bounded Sequence'],
    key_concepts_vi: '• Dãy tăng nếu $u_{n+1} > u_n, \\forall n$; dãy giảm nếu $u_{n+1} < u_n, \\forall n$.\n• Bị chặn trên nếu $u_n \\le M$; bị chặn dưới nếu $u_n \\ge m$.',
    key_concepts_en: '• Increasing if $u_{n+1} > u_n$; decreasing if $u_{n+1} < u_n$.\n• Bounded if $m \\le u_n \\le M$.',
    formulas: [],
    types: [
      {
        id: 'type-11-5-1',
        lesson_id: 'les-11-2-1',
        code: 'Dạng 1',
        title_vi: 'Xét tính tăng giảm và tính bị chặn của dãy số',
        title_en: 'Monotonicity and Boundedness of Sequences',
        order_index: 1,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-2-2',
    chapter_id: 'chap-11-2',
    topic_id: 'top-11-2-2',
    title_vi: 'Bài 6. Cấp số cộng',
    title_en: 'Lesson 6. Arithmetic Progressions',
    order_index: 2,
    learning_objectives: [
      'Tính công sai $d$, số hạng $u_n = u_1 + (n-1)d$ và tổng $S_n$',
      'Giải bài toán tiết kiệm tích luỹ định kỳ và sắp xếp dãy chỗ ngồi',
    ],
    vocabulary_list: ['Arithmetic Progression', 'Common Difference', 'Sum Formula', 'Periodic Savings'],
    key_concepts_vi: '• Công thức: $u_n = u_1 + (n - 1)d$.\n• Tổng $n$ số hạng đầu: $S_n = \\frac{n(u_1 + u_n)}{2} = \\frac{n[2u_1 + (n-1)d]}{2}$.',
    key_concepts_en: '• General term: $u_n = u_1 + (n - 1)d$.\n• Sum: $S_n = \\frac{n(u_1 + u_n)}{2}$.',
    formulas: [
      "u_n = u_1 + (n - 1)d",
      "S_n = \\frac{n(u_1 + u_n)}{2}",
    ],
    types: [
      {
        id: 'type-11-6-1',
        lesson_id: 'les-11-2-2',
        code: 'Dạng 1',
        title_vi: 'Tìm các yếu tố của cấp số cộng (số hạng đầu, công sai, số hạng thứ n)',
        title_en: 'Find Terms and Common Difference of AP',
        order_index: 1,
      },
      {
        id: 'type-11-6-2',
        lesson_id: 'les-11-2-2',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tính tổng số cọc gỗ, số ghế nhà hát và kế hoạch tiết kiệm tiền',
        title_en: 'Real-world Application: Theater Seating Capacity and Structured Savings Plan',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-2-3',
    chapter_id: 'chap-11-2',
    topic_id: 'top-11-2-3',
    title_vi: 'Bài 7. Cấp số nhân',
    title_en: 'Lesson 7. Geometric Progressions',
    order_index: 3,
    learning_objectives: [
      'Tính công bội $q$, số hạng tổng quát $u_n = u_1 \\cdot q^{n-1}$ và tổng $S_n$',
      'Ứng dụng cấp số nhân tính bài toán lãi kép ngân hàng và tăng trưởng vi sinh vật',
    ],
    vocabulary_list: ['Geometric Progression', 'Common Ratio', 'Compound Interest', 'Exponential Growth'],
    key_concepts_vi: '• Số hạng tổng quát: $u_n = u_1 \\cdot q^{n-1}$.\n• Tổng $n$ số hạng đầu: $S_n = \\frac{u_1(1 - q^n)}{1 - q}$ ($q \\neq 1$).\n• Lãi kép: $A_n = A_0(1 + r)^n$.',
    key_concepts_en: '• General term: $u_n = u_1 \\cdot q^{n-1}$.\n• Sum: $S_n = \\frac{u_1(1 - q^n)}{1 - q}$.\n• Compound interest: $A_n = A_0(1 + r)^n$.',
    formulas: [
      "u_n = u_1 \\cdot q^{n-1}",
      "S_n = \\frac{u_1(1 - q^n)}{1 - q} \\quad (q \\neq 1)",
      "A_n = A_0(1 + r)^n",
    ],
    types: [
      {
        id: 'type-11-7-1',
        lesson_id: 'les-11-2-3',
        code: 'Dạng 1',
        title_vi: 'Tìm các yếu tố của cấp số nhân (u1, công bội q, số hạng un, tổng Sn)',
        title_en: 'Find GP Terms, Common Ratio, and Sum',
        order_index: 1,
      },
      {
        id: 'type-11-7-2',
        lesson_id: 'les-11-2-3',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Bài toán lãi kép ngân hàng gửi tiền, tăng trưởng dân số, phân chia tế bào',
        title_en: 'Real-world Application: Bank Compound Interest, Population Growth, Bacterial Cell Division',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 11: CÁC CHƯƠNG III, IV, V, VI, VII, VIII
  // =========================================================================
  {
    id: 'les-11-3-1',
    chapter_id: 'chap-11-3',
    topic_id: 'top-11-3-1',
    title_vi: 'Bài 8. Mẫu số liệu ghép nhóm & Các số đặc trưng xu thế trung tâm',
    title_en: 'Lesson 8. Measures of Central Tendency for Grouped Data',
    order_index: 1,
    learning_objectives: ['Tính số trung bình, trung vị, tứ phân vị và mốt của mẫu số liệu ghép nhóm'],
    vocabulary_list: ['Grouped Mean', 'Median', 'Mode', 'Grouped Data Analysis'],
    key_concepts_vi: '• Số trung bình $\\bar{x} = \\frac{\\sum n_i c_i}{n}$.\n• Trung vị $M_e = u_m + \\frac{\\frac{n}{2} - C}{n_m}(u_{m+1} - u_m)$.',
    key_concepts_en: '• Mean $\\bar{x} = \\frac{\\sum n_i c_i}{n}$.\n• Median $M_e = u_m + \\frac{n/2 - C}{n_m}(u_{m+1} - u_m)$.',
    formulas: [],
    types: [
      {
        id: 'type-11-8-1',
        lesson_id: 'les-11-3-1',
        code: 'Dạng 1',
        title_vi: 'Tính số trung bình, trung vị, mốt của mẫu số liệu ghép nhóm',
        title_en: 'Calculate Mean, Median, Mode for Grouped Data',
        order_index: 1,
      },
      {
        id: 'type-11-8-2',
        lesson_id: 'les-11-3-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Thống kê thu nhập bình quân và phân tích mức tiêu thụ điện gia đình',
        title_en: 'Real-world Application: Household Electricity Consumption and Average Wage Analysis',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-4-1',
    chapter_id: 'chap-11-4',
    topic_id: 'top-11-4-1',
    title_vi: 'Bài 9. Đường thẳng và mặt phẳng song song',
    title_en: 'Lesson 9. Parallel Lines and Planes in Space',
    order_index: 1,
    learning_objectives: ['Chứng minh đường thẳng song song mặt phẳng, hai mặt phẳng song song'],
    vocabulary_list: ['Parallel Lines', 'Parallel Planes', 'Spatial Geometry'],
    key_concepts_vi: '• $d \\not\\subset (\\alpha)$ và $d \\parallel d\' \\subset (\\alpha) \\implies d \\parallel (\\alpha)$.\n• Hai đường thẳng cắt nhau của $(\\alpha)$ song song với $(\\beta) \\implies (\\alpha) \\parallel (\\beta)$.',
    key_concepts_en: '• Line parallel to plane: $d \\parallel d\' \\subset (\\alpha) \\implies d \\parallel (\\alpha)$.\n• Two intersecting lines parallel to plane $\\implies$ planes parallel.',
    formulas: [],
    types: [
      {
        id: 'type-11-9-1',
        lesson_id: 'les-11-4-1',
        code: 'Dạng 1',
        title_vi: 'Chứng minh đường thẳng song song mặt phẳng, hai mặt phẳng song song',
        title_en: 'Prove Parallel Lines and Planes',
        order_index: 1,
      },
      {
        id: 'type-11-4-2',
        lesson_id: 'les-11-4-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Kết cấu giàn giáo song song, các sàn tầng nhà trong xây dựng',
        title_en: 'Real-world Application: Scaffolding Structure and Multi-story Building Floor Placements',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-5-1',
    chapter_id: 'chap-11-5',
    topic_id: 'top-11-5-1',
    title_vi: 'Bài 10. Giới hạn và hàm số liên tục',
    title_en: 'Lesson 10. Limits and Continuous Functions',
    order_index: 1,
    learning_objectives: ['Tính giới hạn vô định $0/0, \\infty/\\infty$, xét tính liên tục và vận tốc tức thời'],
    vocabulary_list: ['Limit of Sequence', 'Limit of Function', 'Continuity', 'Instantaneous Speed'],
    key_concepts_vi: '• Giới hạn hàm số: $\\lim_{x \\to x_0} f(x) = L$.\n• Hàm số liên tục tại $x_0 \\iff \\lim_{x \\to x_0} f(x) = f(x_0)$.\n• Vận tốc tức thời: $v(t) = \\lim_{\\Delta t \\to 0} \\frac{\\Delta s}{\\Delta t}$.',
    key_concepts_en: '• Continuous at $x_0 \\iff \\lim_{x \\to x_0} f(x) = f(x_0)$.\n• Instantaneous velocity: $v(t) = \\lim_{\\Delta t \\to 0} \\frac{\\Delta s}{\\Delta t}$.',
    formulas: [
      "\\lim_{x \\to x_0} f(x) = f(x_0) \\iff f(x) \\text{ liên tục tại } x_0",
    ],
    types: [
      {
        id: 'type-11-10-1',
        lesson_id: 'les-11-5-1',
        code: 'Dạng 1',
        title_vi: 'Tính giới hạn của dãy số và khử các dạng vô định của giới hạn hàm số',
        title_en: 'Compute Limits and Resolve Indeterminate Forms',
        order_index: 1,
      },
      {
        id: 'type-11-10-2',
        lesson_id: 'les-11-5-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tính vận tốc tức thời của vật rơi tự do, cường độ dòng điện tức thời',
        title_en: 'Real-world Application: Free Fall Instantaneous Speed and Transient Electric Current',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-6-1',
    chapter_id: 'chap-11-6',
    topic_id: 'top-11-6-1',
    title_vi: 'Bài 11. Hàm số mũ và hàm số lôgarit',
    title_en: 'Lesson 11. Exponential and Logarithmic Functions',
    order_index: 1,
    learning_objectives: [
      'Biến đổi luỹ thừa, logarit và giải phương trình mũ, logarit',
      'Ứng dụng đo nồng độ axit pH hoá học, thang đo độ Richter động đất, phóng xạ $C_{14}$',
    ],
    vocabulary_list: ['Exponential Function', 'Logarithmic Function', 'pH Scale', 'Richter Scale', 'Carbon-14 Dating'],
    key_concepts_vi: '• Đẳng thức cơ bản: $\\log_a(xy) = \\log_a x + \\log_a y$, $\\log_a(x^\\alpha) = \\alpha\\log_a x$.\n• Độ pH: $\\text{pH} = -\\log_{10}[H^+]$.\n• Độ Richter: $M = \\log_{10}\\left(\\frac{A}{A_0}\\right)$.\n• Định tuổi Carbon: $N(t) = N_0 \\cdot e^{-\\lambda t}$.',
    key_concepts_en: '• $\\log_a(xy) = \\log_a x + \\log_a y$.\n• $\\text{pH} = -\\log_{10}[H^+]$.\n• Richter magnitude $M = \\log_{10}(A/A_0)$.',
    formulas: [
      "\\text{pH} = -\\log_{10}[H^+]",
      "M = \\log_{10}\\left(\\frac{A}{A_0}\\right)",
      "N(t) = N_0 e^{-\\lambda t}",
    ],
    types: [
      {
        id: 'type-11-11-1',
        lesson_id: 'les-11-6-1',
        code: 'Dạng 1',
        title_vi: 'Rút gọn biểu thức luỹ thừa, logarit và giải phương trình mũ, logarit',
        title_en: 'Simplify Logs and Solve Exponential Equations',
        order_index: 1,
      },
      {
        id: 'type-11-11-2',
        lesson_id: 'les-11-6-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Độ pH dung dịch hoá học, thang đo động đất Richter, phân rã phóng xạ',
        title_en: 'Real-world Application: Chemical pH Scale, Earthquake Richter Magnitude, Radioactive Decay',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-7-1',
    chapter_id: 'chap-11-7',
    topic_id: 'top-11-7-1',
    title_vi: 'Bài 12. Đạo hàm và ứng dụng',
    title_en: 'Lesson 12. Derivatives and Tangents',
    order_index: 1,
    learning_objectives: ['Tính đạo hàm bằng công thức, viết phương trình tiếp tuyến, vận tốc và gia tốc'],
    vocabulary_list: ['Derivative Rules', 'Tangent Line', 'Velocity', 'Acceleration'],
    key_concepts_vi: '• Phương trình tiếp tuyến tại $M_0(x_0; y_0)$: $y = f\'(x_0)(x - x_0) + y_0$.\n• Vận tốc tức thời $v(t) = s\'(t)$; Gia tốc tức thời $a(t) = v\'(t) = s\'\'(t)$.',
    key_concepts_en: '• Tangent line: $y = f\'(x_0)(x - x_0) + y_0$.\n• Velocity $v(t) = s\'(t)$; Acceleration $a(t) = s\'\'(t)$.',
    formulas: [
      "y = f'(x_0)(x - x_0) + y_0",
      "v(t) = s'(t); \\quad a(t) = v'(t) = s''(t)",
    ],
    types: [
      {
        id: 'type-11-12-1',
        lesson_id: 'les-11-7-1',
        code: 'Dạng 1',
        title_vi: 'Tính đạo hàm của các hàm số và viết phương trình tiếp tuyến của đồ thị',
        title_en: 'Calculate Derivatives and Find Tangent Line Equations',
        order_index: 1,
      },
      {
        id: 'type-11-12-2',
        lesson_id: 'les-11-7-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Tính vận tốc tức thời, gia tốc chuyển động tên lửa, tốc độ lây lan dịch bệnh',
        title_en: 'Real-world Application: Rocket Instantaneous Velocity, Acceleration and Epidemic Growth Rate',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-11-8-1',
    chapter_id: 'chap-11-8',
    topic_id: 'top-11-8-1',
    title_vi: 'Bài 13. Quan hệ vuông góc trong không gian',
    title_en: 'Lesson 13. Orthogonality in Spatial Geometry',
    order_index: 1,
    learning_objectives: ['Chứng minh đường vuông góc mặt, hai mặt phẳng vuông góc, tính góc và khoảng cách'],
    vocabulary_list: ['Perpendicularity', 'Distance in Space', 'Dihedral Angle', 'Roof Drainage Slope'],
    key_concepts_vi: '• $d \\perp a, d \\perp b$ ($a, b$ cắt nhau trong $(P)$) $\\implies d \\perp (P)$.\n• Khoảng cách từ điểm $M$ đến mặt phẳng $(P)$ là độ dài đoạn $MH \\perp (P)$.',
    key_concepts_en: '• $d$ perpendicular to 2 intersecting lines $\\implies d \\perp (P)$.\n• Distance from $M$ to $(P)$ is length of perpendicular segment $MH$.',
    formulas: [],
    types: [
      {
        id: 'type-11-13-1',
        lesson_id: 'les-11-8-1',
        code: 'Dạng 1',
        title_vi: 'Chứng minh đường vuông góc mặt phẳng, tính khoảng cách từ điểm đến mặt phẳng',
        title_en: 'Orthogonality Proofs and Distance Calculations',
        order_index: 1,
      },
      {
        id: 'type-11-8-2',
        lesson_id: 'les-11-8-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Đo góc dốc thoát nước mái nhà, kiểm tra độ thẳng đứng cột trụ công trình',
        title_en: 'Real-world Application: Roof Drainage Slope Angle and Structural Pillar Verticality Test',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 10: TOÀN BỘ 7 CHƯƠNG CHUẨN KNTT
  // =========================================================================
  {
    id: 'les-10-1-1',
    chapter_id: 'chap-10-1',
    topic_id: 'top-10-1-1',
    title_vi: 'Bài 1. Mệnh đề và tập hợp',
    title_en: 'Lesson 1. Propositions and Sets',
    order_index: 1,
    learning_objectives: [
      'Xác định tính đúng/sai của mệnh đề, lập mệnh đề phủ định, mệnh đề kéo theo',
      'Thực hiện các phép toán giao, hợp, hiệu của tập hợp và vẽ biểu đồ Venn',
    ],
    vocabulary_list: ['Proposition', 'Negation', 'Implication', 'Set Operations', 'Venn Diagram', 'Database Query'],
    key_concepts_vi: '• Mệnh đề là câu khẳng định có tính đúng hoặc sai.\n• Phép toán tập hợp: $A \\cap B$ (giao), $A \\cup B$ (hợp), $A \\setminus B$ (hiệu).\n• Ứng dụng: Điều kiện logic trong thuật toán và truy vấn cơ sở dữ liệu SQL (AND, OR, NOT).',
    key_concepts_en: '• Proposition is a statement that is either True or False.\n• Set operations: $A \\cap B$ (intersection), $A \\cup B$ (union), $A \\setminus B$ (difference).',
    formulas: [
      "A \\cap B = \\{x \\mid x \\in A \\land x \\in B\\}",
      "A \\cup B = \\{x \\mid x \\in A \\lor x \\in B\\}",
    ],
    types: [
      {
        id: 'type-10-1-1',
        lesson_id: 'les-10-1-1',
        code: 'Dạng 1',
        title_vi: 'Xét tính đúng sai của mệnh đề, tìm mệnh đề phủ định',
        title_en: 'Determine Truth Value and Negation of Propositions',
        order_index: 1,
      },
      {
        id: 'type-10-1-2',
        lesson_id: 'les-10-1-1',
        code: 'Dạng 2',
        title_vi: 'Thực hiện các phép toán giao, hợp, hiệu trên tập hợp số',
        title_en: 'Set Operations (Union, Intersection, Difference)',
        order_index: 2,
      },
      {
        id: 'type-10-1-3',
        lesson_id: 'les-10-1-1',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Biểu đồ Venn giải bài toán phân loại nhân sự và câu lạc bộ học sinh',
        title_en: 'Real-world Application: Venn Diagram for Survey Classification and Student Clubs',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-10-2-1',
    chapter_id: 'chap-10-2',
    topic_id: 'top-10-2-1',
    title_vi: 'Bài 2. Bất phương trình và hệ bất phương trình bậc nhất hai ẩn',
    title_en: 'Lesson 2. Linear Inequalities and Systems in Two Variables',
    order_index: 1,
    learning_objectives: [
      'Biểu diễn miền nghiệm của bất phương trình và hệ bất phương trình bậc nhất hai ẩn trên toạ độ Oxy',
      'Giải bài toán quy hoạch tuyến tính tối ưu hoá lợi nhuận kinh doanh xưởng sản xuất',
    ],
    vocabulary_list: ['Linear Inequality', 'Feasible Region', 'Linear Programming', 'Profit Optimization'],
    key_concepts_vi: '• Miền nghiệm của hệ BPT bậc nhất hai ẩn là miền đa giác lồi trên mặt phẳng $Oxy$.\n• Giá trị lớn nhất/nhỏ nhất của hàm mục tiêu $F(x; y) = ax + by$ luôn đạt tại một trong các đỉnh của miền đa giác.',
    key_concepts_en: '• Feasible region is a convex polygon on Oxy.\n• Optimal value of $F(x, y) = ax + by$ occurs at one of the polygon vertices.',
    formulas: [
      "Ax + By \\le C",
      "F(x; y) = ax + by",
    ],
    types: [
      {
        id: 'type-10-2-1',
        lesson_id: 'les-10-2-1',
        code: 'Dạng 1',
        title_vi: 'Xác định miền nghiệm của bất phương trình và hệ bất phương trình bậc nhất 2 ẩn',
        title_en: 'Graph Feasible Region of Linear Inequality Systems',
        order_index: 1,
      },
      {
        id: 'type-10-2-2',
        lesson_id: 'les-10-2-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Bài toán quy hoạch tuyến tính tối ưu hoá lợi nhuận và chi phí sản xuất xưởng',
        title_en: 'Real-world Application: Linear Programming for Factory Production and Profit Maximization',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-10-3-1',
    chapter_id: 'chap-10-3',
    topic_id: 'top-10-3-1',
    title_vi: 'Bài 3. Hệ thức lượng trong tam giác',
    title_en: 'Lesson 3. Trigonometric Relations in Triangles',
    order_index: 1,
    learning_objectives: [
      'Nắm vững định lý côsin: $a^2 = b^2 + c^2 - 2bc\\cos A$, định lý sin: $\\frac{a}{\\sin A} = 2R$',
      'Tính diện tích tam giác theo công thức Heron và giải bài toán đo đạc thực địa',
    ],
    vocabulary_list: ['Law of Cosines', 'Law of Sines', 'Heron Formula', 'Surveying', 'Inaccessible Distance'],
    key_concepts_vi: '• Định lý Côsin: $a^2 = b^2 + c^2 - 2bc\\cos A$.\n• Định lý Sin: $\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R$.\n• Diện tích: $S = \\frac{1}{2}ab\\sin C = \\sqrt{p(p-a)(p-b)(p-c)}$.',
    key_concepts_en: '• Law of Cosines: $a^2 = b^2 + c^2 - 2bc\\cos A$.\n• Law of Sines: $\\frac{a}{\\sin A} = 2R$.\n• Area: $S = \\frac{1}{2}ab\\sin C = \\sqrt{p(p-a)(p-b)(p-c)}$.',
    formulas: [
      "a^2 = b^2 + c^2 - 2bc \\cos A",
      "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R",
      "S = \\sqrt{p(p-a)(p-b)(p-c)}",
    ],
    types: [
      {
        id: 'type-10-3-1',
        lesson_id: 'les-10-3-1',
        code: 'Dạng 1',
        title_vi: 'Giải tam giác (tính cạnh, góc, bán kính đường tròn ngoại tiếp, nội tiếp)',
        title_en: 'Triangle Solving with Laws of Sines and Cosines',
        order_index: 1,
      },
      {
        id: 'type-10-3-2',
        lesson_id: 'les-10-3-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Đo khoảng cách giữa 2 điểm trên biển không tới được, chiều cao ngọn núi',
        title_en: 'Real-world Application: Inaccessible Distance and Mountain/Lighthouse Height Surveying',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-10-4-1',
    chapter_id: 'chap-10-4',
    topic_id: 'top-10-4-1',
    title_vi: 'Bài 4. Vectơ và các phép toán',
    title_en: 'Lesson 4. Vectors and Operations in the Plane',
    order_index: 1,
    learning_objectives: [
      'Thực hiện phép cộng, trừ vectơ, tích vectơ với một số và tích vô hướng',
      'Ứng dụng tính hợp lực tác dụng lên vật và công cơ học sinh ra: $A = \\vec{F} \\cdot \\vec{d}$',
    ],
    vocabulary_list: ['Vector Addition', 'Dot Product', 'Resultant Force', 'Mechanical Work'],
    key_concepts_vi: '• Quy tắc hình bình hành: $\\vec{AB} + \\vec{AD} = \\vec{AC}$.\n• Tích vô hướng: $\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos(\\vec{a}, \\vec{b})$.\n• Công cơ học: $A = \\vec{F} \\cdot \\vec{d} = F \\cdot d \\cdot \\cos \\alpha$.',
    key_concepts_en: '• Parallelogram rule: $\\vec{AB} + \\vec{AD} = \\vec{AC}$.\n• Dot product: $\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos\\theta$.\n• Mechanical work: $A = \\vec{F} \\cdot \\vec{d}$.',
    formulas: [
      "\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}| \\cos(\\vec{a}, \\vec{b})",
      "A = \\vec{F} \\cdot \\vec{d} = F \\cdot d \\cdot \\cos \\alpha",
    ],
    types: [
      {
        id: 'type-10-4-1',
        lesson_id: 'les-10-4-1',
        code: 'Dạng 1',
        title_vi: 'Thực hiện phép toán vectơ, chứng minh đẳng thức và 3 điểm thẳng hàng',
        title_en: 'Vector Operations and Collinearity Proofs',
        order_index: 1,
      },
      {
        id: 'type-10-4-2',
        lesson_id: 'les-10-4-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Hợp lực của hai lực kéo, vận tốc thuyền qua sông, công cơ học',
        title_en: 'Real-world Application: Resultant of Tension Forces, River Boat Velocity, Mechanical Work',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-10-5-1',
    chapter_id: 'chap-10-5',
    topic_id: 'top-10-5-1',
    title_vi: 'Bài 5. Thống kê và các số đặc trưng',
    title_en: 'Lesson 5. Statistics and Descriptive Measures',
    order_index: 1,
    learning_objectives: ['Tính số gần đúng, sai số tuyệt đối, số trung bình, phương sai, độ lệch chuẩn'],
    vocabulary_list: ['Approximation Error', 'Relative Error', 'Mean', 'Standard Deviation'],
    key_concepts_vi: '• Sai số tuyệt đối: $\\Delta_a = |\\bar{a} - a| \\le d$.\n• Số trung bình $\\bar{x}$, phương sai $s^2$, độ lệch chuẩn $s = \\sqrt{s^2}$.',
    key_concepts_en: '• Absolute error: $\\Delta_a = |\\bar{a} - a| \\le d$.\n• Standard deviation $s = \\sqrt{s^2}$.',
    formulas: [],
    types: [
      {
        id: 'type-10-5-1',
        lesson_id: 'les-10-5-1',
        code: 'Dạng 1',
        title_vi: 'Quy tròn số gần đúng và tính các số đặc trưng đo xu thế trung tâm',
        title_en: 'Rounding and Measures of Central Tendency',
        order_index: 1,
      },
      {
        id: 'type-10-5-2',
        lesson_id: 'les-10-5-1',
        code: 'Dạng 2 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Đánh giá độ tin cậy kết quả đo lường và chất lượng học tập',
        title_en: 'Real-world Application: Measurement Error Tolerance and Academic Performance Consistency',
        order_index: 2,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-10-6-1',
    chapter_id: 'chap-10-6',
    topic_id: 'top-10-6-1',
    title_vi: 'Bài 6. Hàm số bậc hai & Đồ thị Parabol',
    title_en: 'Lesson 6. Quadratic Functions and Parabola Graphs',
    order_index: 1,
    learning_objectives: [
      'Xác định toạ độ đỉnh $I(-b/2a, -\\Delta/4a)$, trục đối xứng $x = -b/2a$ và vẽ parabol',
      'Ứng dụng quỹ đạo bay ném bóng, bắn pháo hoa, vòm cầu Parabol',
    ],
    vocabulary_list: ['Quadratic Function', 'Parabola Vertex', 'Trajectory', 'Arch Bridge Design'],
    key_concepts_vi: '• Parabol $y = ax^2 + bx + c$ ($a \\neq 0$) có đỉnh $I\\left(-\\frac{b}{2a}; -\\frac{\\Delta}{4a}\\right)$, trục đối xứng $x = -\\frac{b}{2a}$.\n• Bề lõm quay lên nếu $a > 0$, quay xuống nếu $a < 0$.\n• Quỹ đạo chuyển động ném xiên: $h(t) = -\\frac{1}{2}gt^2 + v_0 t + h_0$.',
    key_concepts_en: '• Parabola vertex $I(-b/2a, -\\Delta/4a)$, axis of symmetry $x = -b/2a$.\n• Projectile motion formula: $h(t) = -\\frac{1}{2}gt^2 + v_0 t + h_0$.',
    formulas: [
      "y = ax^2 + bx + c \\quad (a \\neq 0)",
      "x_I = -\\frac{b}{2a}; \\quad y_I = -\\frac{\\Delta}{4a}",
      "h(t) = -\\frac{1}{2}gt^2 + v_0 t + h_0",
    ],
    types: [
      {
        id: 'type-10-6-1',
        lesson_id: 'les-10-6-1',
        code: 'Dạng 1',
        title_vi: 'Xác định toạ độ đỉnh, trục đối xứng và vẽ đồ thị hàm số bậc hai',
        title_en: 'Find Vertex, Axis of Symmetry, and Graph Quadratic Functions',
        order_index: 1,
      },
      {
        id: 'type-10-6-2',
        lesson_id: 'les-10-6-1',
        code: 'Dạng 2',
        title_vi: 'Xét dấu tam thức bậc hai và giải bất phương trình bậc hai',
        title_en: 'Quadratic Inequalities and Sign Charts',
        order_index: 2,
      },
      {
        id: 'type-10-6-3',
        lesson_id: 'les-10-6-1',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Quỹ đạo bắn pháo hoa, vòm cổng Parabol, tối ưu diện tích đất rào chắn',
        title_en: 'Real-world Application: Firework Trajectory, Parabolic Arch Bridge, and Fenced Land Area Optimization',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  {
    id: 'les-10-7-1',
    chapter_id: 'chap-10-7',
    topic_id: 'top-10-7-1',
    title_vi: 'Bài 7. Phương pháp toạ độ trong mặt phẳng & Ba đường Conic',
    title_en: 'Lesson 7. Coordinate Geometry in the Plane and Conic Sections',
    order_index: 1,
    learning_objectives: [
      'Viết phương trình đường thẳng, đường tròn và ba đường conic (Elip, Hyperbol, Parabol)',
      'Ứng dụng quỹ đạo vệ tinh Elip, tháp làm mát Hyperbol, gương phản xạ Parabol',
    ],
    vocabulary_list: ['Line Equation', 'Circle Equation', 'Ellipse', 'Hyperbola', 'Conic Sections', 'Satellite Orbit'],
    key_concepts_vi: '• Đường thẳng: $Ax + By + C = 0$.\n• Đường tròn: $(x - a)^2 + (y - b)^2 = R^2$.\n• Elip: $\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1$ ($a^2 = b^2 + c^2$).\n• Hyperbol: $\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1$ ($c^2 = a^2 + b^2$).\n• Parabol: $y^2 = 2px$.',
    key_concepts_en: '• Ellipse: $\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1$.\n• Hyperbola: $\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1$.\n• Parabola: $y^2 = 2px$.',
    formulas: [
      "\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1 \\quad (a > b > 0, c^2 = a^2 - b^2)",
      "\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1 \\quad (c^2 = a^2 + b^2)",
      "y^2 = 2px \\quad (p > 0)",
    ],
    types: [
      {
        id: 'type-10-7-1',
        lesson_id: 'les-10-7-1',
        code: 'Dạng 1',
        title_vi: 'Viết phương trình đường thẳng, tính góc và khoảng cách từ điểm đến đường thẳng',
        title_en: 'Line Equations, Angle and Distance in Oxy Plane',
        order_index: 1,
      },
      {
        id: 'type-10-7-2',
        lesson_id: 'les-10-7-1',
        code: 'Dạng 2',
        title_vi: 'Lập phương trình đường tròn và phương trình chính tắc của ba đường Conic',
        title_en: 'Circle Equations and Canonical Conic Sections',
        order_index: 2,
      },
      {
        id: 'type-10-7-3',
        lesson_id: 'les-10-7-1',
        code: 'Dạng 3 (Ứng dụng thực tế)',
        title_vi: 'Ứng dụng thực tế: Quỹ đạo elip của các hành tinh, gương hội tụ parabol, tháp làm mát hyperbol',
        title_en: 'Real-world Application: Elliptic Planetary Orbit, Parabolic Solar Concentrator, Hyperbolic Cooling Tower',
        order_index: 3,
      },
    ],
    worked_examples: [],
    status: 'PUBLISHED',
    language_level: 2,
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
];
