import { Question, WorkedExample } from '../types';

// =========================================================================
// BỘ BÀI TẬP MẪU CÓ LỜI GIẢI CHI TIẾT THEO TỪNG BÀI HỌC (WORKED EXAMPLES)
// =========================================================================
export const DEFAULT_WORKED_EXAMPLES: Record<string, WorkedExample[]> = {
  // LỚP 11 - BÀI 5: DÃY SỐ
  'les-11-2-1': [
    {
      id: 'we-11-5-1',
      type_id: 'type-11-5-1',
      type_code: 'Dạng 1. Xét tính tăng, giảm và bị chặn của dãy số',
      title_vi: 'Ví dụ 1: Xét tính tăng/giảm của dãy số phân thức',
      title_en: 'Example 1: Monotonicity of Rational Sequence',
      problem_vi: 'Cho dãy số $(u_n)$ với $u_n = \\frac{2n - 1}{n + 1}$. Chứng minh dãy số $(u_n)$ là dãy số tăng và bị chặn.',
      problem_en: 'Given the sequence $(u_n)$ with $u_n = \\frac{2n - 1}{n + 1}$. Prove that $(u_n)$ is strictly increasing and bounded.',
      solution_vi: '• Xét hiệu $u_{n+1} - u_n = \\frac{2(n+1) - 1}{(n+1) + 1} - \\frac{2n - 1}{n + 1} = \\frac{2n + 1}{n + 2} - \\frac{2n - 1}{n + 1} = \\frac{(2n+1)(n+1) - (2n-1)(n+2)}{(n+2)(n+1)} = \\frac{3}{(n+2)(n+1)} > 0, \\forall n \\ge 1$.\nDo đó $(u_n)$ là dãy số tăng.\n• Mặt khác: $u_n = 2 - \\frac{3}{n+1}$. Vì $n \\ge 1 \\implies \\frac{3}{n+1} \\le \\frac{3}{2} \\implies u_n \\ge 2 - \\frac{3}{2} = \\frac{1}{2}$.\nĐồng thời $\\frac{3}{n+1} > 0 \\implies u_n < 2$.\nVậy $\\frac{1}{2} \\le u_n < 2, \\forall n \\in \\mathbb{N}^*$, suy ra dãy số $(u_n)$ bị chặn.',
      solution_en: '• Difference $u_{n+1} - u_n = \\frac{3}{(n+2)(n+1)} > 0, \\forall n \\ge 1 \\implies$ strictly increasing.\n• We rewrite $u_n = 2 - \\frac{3}{n+1}$. Since $n \\ge 1$, we have $\\frac{1}{2} \\le u_n < 2, \\forall n \\in \\mathbb{N}^* \\implies$ bounded sequence.',
    },
    {
      id: 'we-11-5-2',
      type_id: 'type-11-5-1',
      type_code: 'Dạng 1. Xét tính bị chặn của dãy số',
      title_vi: 'Ví dụ 2: Tìm số hạng tổng quát và xét tính bị chặn',
      title_en: 'Example 2: General Term and Boundedness',
      problem_vi: 'Cho dãy số $(u_n)$ xác định bởi $u_1 = 1$ và $u_{n+1} = \\frac{u_n}{u_n + 1}, \\forall n \\ge 1$. Tìm công thức số hạng tổng quát $u_n$ và xét tính bị chặn.',
      problem_en: 'Given $(u_n)$ with $u_1 = 1$ and $u_{n+1} = \\frac{u_n}{u_n + 1}$. Find the general term $u_n$ and test for boundedness.',
      solution_vi: 'Nghịch đảo hai vế: $\\frac{1}{u_{n+1}} = \\frac{u_n + 1}{u_n} = \\frac{1}{u_n} + 1$.\nĐặt $v_n = \\frac{1}{u_n} \\implies v_1 = 1, v_{n+1} = v_n + 1$. Đây là cấp số cộng có $v_1 = 1, d = 1 \\implies v_n = 1 + (n - 1) = n$.\nSuy ra $u_n = \\frac{1}{n}$. Vì $0 < u_n \\le 1, \\forall n \\ge 1$ nên dãy số $(u_n)$ bị chặn.',
      solution_en: 'Taking reciprocals: $\\frac{1}{u_{n+1}} = \\frac{1}{u_n} + 1 \\implies v_n = \\frac{1}{u_n} = n \\implies u_n = \\frac{1}{n}$. Since $0 < u_n \\le 1, \\forall n$, $(u_n)$ is bounded.',
    },
  ],

  // LỚP 11 - BÀI 6: CẤP SỐ CỘNG
  'les-11-2-2': [
    {
      id: 'we-11-6-1',
      type_id: 'type-11-6-1',
      type_code: 'Dạng 1. Xác định công sai và số hạng tổng quát của CSC',
      title_vi: 'Ví dụ 1: Tìm số hạng đầu và công sai của cấp số cộng',
      title_en: 'Example 1: Initial Term and Common Difference',
      problem_vi: 'Cho cấp số cộng $(u_n)$ thoả mãn: $\\begin{cases} u_2 + u_5 = 14 \\\\ u_1 + u_6 = 14 \\end{cases}$ và $u_3 + u_7 = 22$. Tìm $u_1$, công sai $d$ và tính tổng $S_{20}$.',
      problem_en: 'Given an arithmetic progression $(u_n)$ satisfying $u_2 + u_5 = 14$ and $u_3 + u_7 = 22$. Find $u_1$, $d$, and calculate $S_{20}$.',
      solution_vi: 'Ta có $\\begin{cases} (u_1 + d) + (u_1 + 4d) = 14 \\\\ (u_1 + 2d) + (u_1 + 6d) = 22 \\end{cases} \\iff \\begin{cases} 2u_1 + 5d = 14 \\\\ 2u_1 + 8d = 22 \\end{cases} \\iff \\begin{cases} 3d = 8 \\implies d = 2 \\\\ u_1 = 2 \\end{cases}$.\nTổng 20 số hạng đầu: $S_{20} = \\frac{20 \\cdot [2(2) + 19(2)]}{2} = 10 \\cdot (4 + 38) = 420$.',
      solution_en: 'Solving the linear system yields $u_1 = 2, d = 2$. Sum $S_{20} = \\frac{20 \\cdot [2(2) + 19(2)]}{2} = 420$.',
    },
    {
      id: 'we-11-6-2',
      type_id: 'type-11-6-2',
      type_code: 'Dạng 2 (Ứng dụng thực tế). Xếp ghế khán đài',
      title_vi: 'Ví dụ 2 (Ứng dụng thực tế): Thiết kế hàng ghế nhà hát',
      title_en: 'Example 2 (Real-world): Theater Seating Layout',
      problem_vi: 'Một rạp hát có 25 hàng ghế. Hàng đầu tiên có 20 ghế, mỗi hàng sau có nhiều hơn hàng liền trước 3 ghế. Hỏi rạp hát có tất cả bao nhiêu ghế ngồi?',
      problem_en: 'A theater has 25 rows of seats. The first row has 20 seats, and each subsequent row has 3 more seats than the previous one. How many total seats are in the theater?',
      solution_vi: 'Số ghế mỗi hàng lập thành một cấp số cộng với $u_1 = 20$, công sai $d = 3$, số hàng $n = 25$.\nTổng số ghế là: $S_{25} = \\frac{25 \\cdot [2(20) + (25 - 1) \\cdot 3]}{2} = \\frac{25 \\cdot (40 + 72)}{2} = \\frac{25 \\cdot 112}{2} = 1400$ ghế.',
      solution_en: 'Seats per row form an AP with $u_1 = 20, d = 3, n = 25$. Total seats $S_{25} = \\frac{25 \\cdot [40 + 72]}{2} = 1400$ seats.',
    },
  ],

  // LỚP 11 - BÀI 7: CẤP SỐ NHÂN
  'les-11-2-3': [
    {
      id: 'we-11-7-1',
      type_id: 'type-11-7-1',
      type_code: 'Dạng 1. Xác định công bội và số hạng tổng quát của CSN',
      title_vi: 'Ví dụ 1: Tìm số hạng và công bội của cấp số nhân',
      title_en: 'Example 1: Common Ratio and General Term of GP',
      problem_vi: 'Cho cấp số nhân $(u_n)$ có $u_1 = 3$ và $u_4 = 24$. Tìm công bội $q$, viết số hạng tổng quát $u_n$ và tính tổng $S_8$.',
      problem_en: 'Given a geometric progression $(u_n)$ with $u_1 = 3$ and $u_4 = 24$. Find the common ratio $q$, write $u_n$, and calculate $S_8$.',
      solution_vi: 'Ta có $u_4 = u_1 \\cdot q^3 \\iff 24 = 3 \\cdot q^3 \\iff q^3 = 8 \\iff q = 2$.\nSố hạng tổng quát: $u_n = 3 \\cdot 2^{n-1}$.\nTổng 8 số hạng đầu: $S_8 = \\frac{u_1(1 - q^8)}{1 - q} = \\frac{3(1 - 2^8)}{1 - 2} = 3(256 - 1) = 765$.',
      solution_en: '$u_4 = u_1 q^3 \\implies q = 2$. General term $u_n = 3 \\cdot 2^{n-1}$. Sum $S_8 = \\frac{3(1 - 2^8)}{1 - 2} = 765$.',
    },
    {
      id: 'we-11-7-2',
      type_id: 'type-11-7-2',
      type_code: 'Dạng 2 (Ứng dụng thực tế). Bài toán lãi kép ngân hàng',
      title_vi: 'Ví dụ 2 (Ứng dụng thực tế): Lãi kép gửi tiết kiệm',
      title_en: 'Example 2 (Real-world): Compound Interest Savings',
      problem_vi: 'Một người gửi 100 triệu đồng vào ngân hàng với lãi suất $6\\%/\\text{năm}$ theo hình thức lãi kép (tiền lãi hàng năm nhập vào vốn). Hỏi sau 5 năm người đó nhận được cả vốn lẫn lãi là bao nhiêu tiền?',
      problem_en: 'A person deposits 100 million VND into a bank with an annual compound interest rate of 6%. How much total amount (principal + interest) will they receive after 5 years?',
      solution_vi: 'Áp dụng công thức lãi kép: $A_n = A_0(1 + r)^n$.\nVới $A_0 = 100\\text{ triệu}$, $r = 0.06$, $n = 5$ năm:\n$A_5 = 100 \\cdot (1 + 0.06)^5 = 100 \\cdot (1.06)^5 \\approx 133.82\\text{ triệu đồng}$.',
      solution_en: 'Compound interest formula: $A_5 = 100 \\cdot (1.06)^5 \\approx 133.82$ million VND.',
    },
  ],

  // LỚP 10 - BÀI 1: MỆNH ĐỀ VÀ TẬP HỢP
  'les-10-1-1': [
    {
      id: 'we-10-1-1',
      type_id: 'type-10-1-1',
      type_code: 'Dạng 1. Xét tính đúng sai của mệnh đề',
      title_vi: 'Ví dụ 1: Phủ định mệnh đề chứa lượng từ',
      title_en: 'Example 1: Negation of Quantified Propositions',
      problem_vi: 'Lập mệnh đề phủ định của mệnh đề $P: \"\\forall x \\in \\mathbb{R}, x^2 - 2x + 3 > 0\"$ và xét tính đúng sai của $P$.',
      problem_en: 'Form the negation of proposition $P: \"\\forall x \\in \\mathbb{R}, x^2 - 2x + 3 > 0\"$ and determine the truth value of $P$.',
      solution_vi: '• Mệnh đề phủ định $\\bar{P}: \"\\exists x \\in \\mathbb{R}, x^2 - 2x + 3 \\le 0\"$.\n• Xét $x^2 - 2x + 3 = (x - 1)^2 + 2 > 0, \\forall x \\in \\mathbb{R}$. Do đó mệnh đề $P$ là mệnh đề ĐÚNG, còn $\\bar{P}$ là mệnh đề SAI.',
      solution_en: '• Negation $\\bar{P}: \"\\exists x \\in \\mathbb{R}, x^2 - 2x + 3 \\le 0\"$.\n• Since $x^2 - 2x + 3 = (x-1)^2 + 2 > 0$ for all real $x$, $P$ is TRUE and $\\bar{P}$ is FALSE.',
    },
  ],

  // LỚP 10 - BÀI 2: BẤT PHƯƠNG TRÌNH BẬC NHẤT HAI ẨN
  'les-10-2-1': [
    {
      id: 'we-10-2-1',
      type_id: 'type-10-2-1',
      type_code: 'Dạng 1. Xác định miền nghiệm',
      title_vi: 'Ví dụ 1: Biểu diễn miền nghiệm của hệ bất phương trình',
      title_en: 'Example 1: Graphing Feasible Region',
      problem_vi: 'Biểu diễn miền nghiệm của hệ bất phương trình: $\\begin{cases} x + y \\le 4 \\\\ 2x - y \\ge 1 \\\\ x \\ge 0, y \\ge 0 \\end{cases}$ trên mặt phẳng toạ độ $Oxy$.',
      problem_en: 'Graph the feasible region of the system $\\begin{cases} x + y \\le 4 \\\\ 2x - y \\ge 1 \\\\ x \\ge 0, y \\ge 0 \\end{cases}$ on the Cartesian coordinate plane.',
      solution_vi: 'Vẽ các đường thẳng $d_1: x + y = 4$, $d_2: 2x - y = 1$, trục $Ox (y=0)$ và $Oy (x=0)$. Miền nghiệm là miền tứ giác với các đỉnh $A(0.5; 0)$, $B(4; 0)$, $C(5/3; 7/3)$.',
      solution_en: 'Draw boundary lines $d_1: x+y=4$ and $d_2: 2x-y=1$. The solution is the polygonal region with vertices at $(0.5, 0), (4, 0), (5/3, 7/3)$.',
    },
  ],

  // LỚP 10 - BÀI 6: HÀM SỐ BẬC HAI & PARABOL
  'les-10-6-1': [
    {
      id: 'we-10-6-1',
      type_id: 'type-10-6-1',
      type_code: 'Dạng 1. Tìm đỉnh và trục đối xứng của Parabol',
      title_vi: 'Ví dụ 1: Khảo sát hàm số bậc hai',
      title_en: 'Example 1: Quadratic Function Vertex and Axis',
      problem_vi: 'Cho hàm số $y = -x^2 + 4x - 3$. Tìm toạ độ đỉnh, trục đối xứng và lập bảng biến thiên của hàm số.',
      problem_en: 'Given $y = -x^2 + 4x - 3$. Find the vertex coordinates, axis of symmetry, and variation table.',
      solution_vi: '• Toạ độ đỉnh: $x_I = -\\frac{b}{2a} = -\\frac{4}{2(-1)} = 2$; $y_I = -(2)^2 + 4(2) - 3 = 1 \\implies I(2; 1)$.\n• Trục đối xứng: đường thẳng $x = 2$.\n• Do $a = -1 < 0$, parabol quay bề lõm xuống dưới. Hàm số đồng biến trên $(-\\infty; 2)$ và nghịch biến trên $(2; +\\infty)$. Giá trị lớn nhất $\\max y = 1$ tại $x = 2$.',
      solution_en: 'Vertex $I(2, 1)$, axis of symmetry $x = 2$. Maximum value is $1$ at $x = 2$.',
    },
  ],
};

// =========================================================================
// NGÂN HÀNG CÂU HỎI CHUẨN 4 DẠNG THỨC GDPT 2018 (FULL_QUESTION_BANK)
// =========================================================================
export const FULL_QUESTION_BANK: Question[] = [
  // =========================================================================
  // LỚP 11 - BÀI 5: DÃY SỐ (top-11-2-1 / les-11-2-1)
  // =========================================================================
  {
    id: 'q-11-5-tn1',
    topic_id: 'top-11-2-1',
    type_id: 'type-11-5-1',
    question_type: 'MCQ',
    format_type: 'TN',
    difficulty: 'EASY',
    language_level: 2,
    question_vi: 'Cho dãy số $(u_n)$ với $u_n = \\frac{n - 1}{n + 1}$. Giá trị của số hạng thứ tư $u_4$ bằng bao nhiêu?',
    question_en: 'Given the sequence $(u_n)$ defined by $u_n = \\frac{n - 1}{n + 1}$. What is the value of the fourth term $u_4$?',
    options: [
      { option_key: 'A', content_vi: '$3/5$', content_en: '$3/5$', is_correct: true },
      { option_key: 'B', content_vi: '$4/5$', content_en: '$4/5$', is_correct: false },
      { option_key: 'C', content_vi: '$2/3$', content_en: '$2/3$', is_correct: false },
      { option_key: 'D', content_vi: '$5/3$', content_en: '$5/3$', is_correct: false },
    ],
    solution_vi: 'Thay $n = 4$ vào công thức số hạng tổng quát: $u_4 = \\frac{4 - 1}{4 + 1} = \\frac{3}{5}$.',
    solution_en: 'Substitute $n = 4$ into the general formula: $u_4 = \\frac{4 - 1}{4 + 1} = \\frac{3}{5}$.',
    correct_answer: 'A',
    math_skill: 'Tính số hạng của dãy số cho bởi công thức tổng quát',
    english_skill: 'Evaluating sequence terms',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-5-tn2',
    topic_id: 'top-11-2-1',
    type_id: 'type-11-5-1',
    question_type: 'MCQ',
    format_type: 'TN',
    difficulty: 'MEDIUM',
    language_level: 2,
    question_vi: 'Trong các dãy số sau, dãy số nào là dãy số tăng?',
    question_en: 'Which of the following sequences is strictly increasing?',
    options: [
      { option_key: 'A', content_vi: '$u_n = 2n + 1$', content_en: '$u_n = 2n + 1$', is_correct: true },
      { option_key: 'B', content_vi: '$u_n = \\frac{1}{n}$', content_en: '$u_n = \\frac{1}{n}$', is_correct: false },
      { option_key: 'C', content_vi: '$u_n = -3n + 2$', content_en: '$u_n = -3n + 2$', is_correct: false },
      { option_key: 'D', content_vi: '$u_n = (-1)^n$', content_en: '$u_n = (-1)^n$', is_correct: false },
    ],
    solution_vi: 'Với $u_n = 2n + 1$, ta có $u_{n+1} - u_n = [2(n+1) + 1] - (2n + 1) = 2 > 0, \\forall n \\in \\mathbb{N}^*$. Do đó đây là dãy số tăng.',
    solution_en: '$u_{n+1} - u_n = 2 > 0, \\forall n \\implies u_n = 2n + 1$ is strictly increasing.',
    correct_answer: 'A',
    math_skill: 'Nhận biết dãy số tăng, giảm',
    english_skill: 'Strictly increasing sequence recognition',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-5-ds1',
    topic_id: 'top-11-2-1',
    type_id: 'type-11-5-1',
    question_type: 'TRUE_FALSE',
    format_type: 'DS',
    difficulty: 'MEDIUM',
    language_level: 2,
    question_vi: 'Cho dãy số $(u_n)$ với $u_n = \\frac{n}{n + 2}$. Xét tính đúng/sai của các mệnh đề sau:',
    question_en: 'Given the sequence $(u_n)$ with $u_n = \\frac{n}{n + 2}$. Determine whether each of the following statements is True (Đ) or False (S):',
    options: [
      { option_key: 'a', content_vi: 'Số hạng đầu tiên của dãy số là $u_1 = \\frac{1}{3}$.', content_en: 'The first term of the sequence is $u_1 = \\frac{1}{3}$.', is_correct: true },
      { option_key: 'b', content_vi: 'Dãy số $(u_n)$ là dãy số giảm.', content_en: 'The sequence $(u_n)$ is strictly decreasing.', is_correct: false },
      { option_key: 'c', content_vi: 'Ta có $u_n < 1$ với mọi $n \\in \\mathbb{N}^*$.', content_en: 'We have $u_n < 1$ for all $n \\in \\mathbb{N}^*$.', is_correct: true },
      { option_key: 'd', content_vi: 'Dãy số $(u_n)$ là dãy số bị chặn.', content_en: 'The sequence $(u_n)$ is bounded.', is_correct: true },
    ],
    solution_vi: 'a) Đúng ($u_1 = 1/3$). b) Sai (xét $u_{n+1} - u_n = \\frac{n+1}{n+3} - \\frac{n}{n+2} = \\frac{2}{(n+3)(n+2)} > 0$ nên $(u_n)$ là dãy tăng). c) Đúng (vì $n < n + 2$). d) Đúng (vì $1/3 \\le u_n < 1$).',
    solution_en: 'a) True. b) False (it is strictly increasing). c) True ($n < n + 2$). d) True ($1/3 \\le u_n < 1$).',
    correct_answer: 'a-Đ, b-S, c-Đ, d-Đ',
    math_skill: 'Khảo sát tính chất toàn diện của dãy số',
    english_skill: 'True/False evaluation of sequence properties',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-5-tln1',
    topic_id: 'top-11-2-1',
    type_id: 'type-11-5-1',
    question_type: 'SHORT',
    format_type: 'TLN',
    difficulty: 'HARD',
    language_level: 2,
    question_vi: 'Cho dãy số $(u_n)$ xác định bởi hệ thức truy hồi: $u_1 = 3$ và $u_{n+1} = u_n + 4, \\forall n \\ge 1$. Giá trị của số hạng thứ mười $u_{10}$ bằng bao nhiêu?',
    question_en: 'Given a recursive sequence with $u_1 = 3$ and $u_{n+1} = u_n + 4, \\forall n \\ge 1$. What is the numeric value of the 10th term $u_{10}$?',
    solution_vi: 'Dãy số là cấp số cộng có số hạng đầu $u_1 = 3$, công sai $d = 4$. Số hạng thứ 10 là: $u_{10} = u_1 + 9d = 3 + 9(4) = 39$.',
    solution_en: 'Arithmetic progression with $u_1 = 3, d = 4$. The 10th term is $u_{10} = 3 + 9(4) = 39$.',
    correct_answer: '39',
    math_skill: 'Tính số hạng từ công thức truy hồi',
    english_skill: 'Numeric term evaluation',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-5-tl1',
    topic_id: 'top-11-2-1',
    type_id: 'type-11-5-1',
    question_type: 'ESSAY',
    format_type: 'TL',
    difficulty: 'HARD',
    language_level: 3,
    question_vi: 'Cho dãy số $(u_n)$ với số hạng tổng quát $u_n = \\frac{3n - 2}{n + 1}$. Chứng minh rằng $(u_n)$ là dãy số tăng và bị chặn.',
    question_en: 'Given $(u_n)$ with $u_n = \\frac{3n - 2}{n + 1}$. Prove that $(u_n)$ is strictly increasing and bounded.',
    solution_vi: '1) Tính hiệu: $u_{n+1} - u_n = \\frac{3(n+1)-2}{n+2} - \\frac{3n-2}{n+1} = \\frac{3n+1}{n+2} - \\frac{3n-2}{n+1} = \\frac{(3n+1)(n+1) - (3n-2)(n+2)}{(n+2)(n+1)} = \\frac{5}{(n+2)(n+1)} > 0, \\forall n \\ge 1$.\nVậy $(u_n)$ là dãy số tăng.\n2) Biến đổi: $u_n = 3 - \\frac{5}{n+1}$. Với mọi $n \\ge 1$, ta có $0 < \\frac{5}{n+1} \\le \\frac{5}{2} \\implies \\frac{1}{2} \\le u_n < 3$.\nVậy dãy số $(u_n)$ bị chặn.',
    solution_en: '1) Difference $u_{n+1} - u_n = \\frac{5}{(n+2)(n+1)} > 0 \\implies$ strictly increasing.\n2) $u_n = 3 - \\frac{5}{n+1} \\implies \\frac{1}{2} \\le u_n < 3 \\implies$ bounded.',
    correct_answer: 'Dãy số tăng và bị chặn trong [1/2; 3)',
    math_skill: 'Chứng minh tính tăng giảm và bị chặn',
    english_skill: 'Proving monotonicity and boundedness',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 11 - BÀI 6: CẤP SỐ CỘNG (top-11-2-2 / les-11-2-2)
  // =========================================================================
  {
    id: 'q-11-6-tn1',
    topic_id: 'top-11-2-2',
    type_id: 'type-11-6-1',
    question_type: 'MCQ',
    format_type: 'TN',
    difficulty: 'EASY',
    language_level: 2,
    question_vi: 'Cho cấp số cộng $(u_n)$ có số hạng đầu $u_1 = 4$ và công sai $d = 3$. Số hạng thứ 6 của cấp số cộng là:',
    question_en: 'For an arithmetic progression $(u_n)$ with first term $u_1 = 4$ and common difference $d = 3$. The 6th term is:',
    options: [
      { option_key: 'A', content_vi: '$19$', content_en: '$19$', is_correct: true },
      { option_key: 'B', content_vi: '$22$', content_en: '$22$', is_correct: false },
      { option_key: 'C', content_vi: '$16$', content_en: '$16$', is_correct: false },
      { option_key: 'D', content_vi: '$20$', content_en: '$20$', is_correct: false },
    ],
    solution_vi: '$u_6 = u_1 + 5d = 4 + 5(3) = 19$.',
    solution_en: '$u_6 = u_1 + 5d = 4 + 15 = 19$.',
    correct_answer: 'A',
    math_skill: 'Tính số hạng thứ n của cấp số cộng',
    english_skill: 'Calculating terms of AP',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-6-ds1',
    topic_id: 'top-11-2-2',
    type_id: 'type-11-6-1',
    question_type: 'TRUE_FALSE',
    format_type: 'DS',
    difficulty: 'MEDIUM',
    language_level: 2,
    question_vi: 'Cho cấp số cộng $(u_n)$ có $u_1 = 2$ và công sai $d = 5$. Xét tính đúng/sai của các mệnh đề sau:',
    question_en: 'Given an arithmetic progression $(u_n)$ with $u_1 = 2$ and $d = 5$. Determine whether each statement is True (Đ) or False (S):',
    options: [
      { option_key: 'a', content_vi: 'Công thức số hạng tổng quát là $u_n = 5n - 3$.', content_en: 'The general term formula is $u_n = 5n - 3$.', is_correct: true },
      { option_key: 'b', content_vi: 'Số 102 là một số hạng của cấp số cộng.', content_en: 'The number 102 is a term in this progression.', is_correct: true },
      { option_key: 'c', content_vi: 'Tổng của 10 số hạng đầu tiên là $S_{10} = 245$.', content_en: 'The sum of the first 10 terms is $S_{10} = 245$.', is_correct: true },
      { option_key: 'd', content_vi: 'Cấp số cộng $(u_n)$ là một dãy số giảm.', content_en: 'The progression $(u_n)$ is strictly decreasing.', is_correct: false },
    ],
    solution_vi: 'a) Đúng ($u_n = 2 + (n-1)5 = 5n - 3$). b) Đúng ($5n - 3 = 102 \\iff 5n = 105 \\iff n = 21$). c) Đúng ($S_{10} = \\frac{10[2(2) + 9(5)]}{2} = 5(49) = 245$). d) Sai ($d = 5 > 0$ nên là dãy tăng).',
    solution_en: 'a) True. b) True ($n = 21$). c) True ($S_{10} = 245$). d) False ($d > 0 \\implies$ increasing).',
    correct_answer: 'a-Đ, b-Đ, c-Đ, d-S',
    math_skill: 'Kiểm tra tính chất và số hạng thuộc CSC',
    english_skill: 'AP properties verification',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-6-tln1',
    topic_id: 'top-11-2-2',
    type_id: 'type-11-6-2',
    question_type: 'SHORT',
    format_type: 'TLN',
    difficulty: 'HARD',
    language_level: 2,
    question_vi: 'Một người thợ xây xếp các viên gạch thành một bức tường hình thang có 15 hàng. Hàng dưới cùng có 50 viên gạch, mỗi hàng trên có ít hơn hàng liền dưới 2 viên. Tổng số viên gạch cần dùng là bao nhiêu viên?',
    question_en: 'A builder stacks bricks in 15 rows. The bottom row has 50 bricks, and each higher row has 2 fewer bricks than the row below. How many total bricks are used?',
    solution_vi: 'Số gạch các hàng lập thành CSC với $u_1 = 50$, $d = -2$, $n = 15$. Tổng $S_{15} = \\frac{15 \\cdot [2(50) + 14(-2)]}{2} = \\frac{15 \\cdot (100 - 28)}{2} = \\frac{15 \\cdot 72}{2} = 540$ viên.',
    solution_en: 'AP with $u_1 = 50, d = -2, n = 15 \\implies S_{15} = 540$ bricks.',
    correct_answer: '540',
    math_skill: 'Ứng dụng thực tế cấp số cộng',
    english_skill: 'Real-world AP word problem',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 11 - BÀI 7: CẤP SỐ NHÂN (top-11-2-3 / les-11-2-3)
  // =========================================================================
  {
    id: 'q-11-7-tn1',
    topic_id: 'top-11-2-3',
    type_id: 'type-11-7-1',
    question_type: 'MCQ',
    format_type: 'TN',
    difficulty: 'EASY',
    language_level: 2,
    question_vi: 'Cho cấp số nhân $(u_n)$ có số hạng đầu $u_1 = 2$ và công bội $q = 3$. Giá trị của $u_4$ bằng:',
    question_en: 'For a geometric progression $(u_n)$ with first term $u_1 = 2$ and common ratio $q = 3$. The value of $u_4$ is:',
    options: [
      { option_key: 'A', content_vi: '$54$', content_en: '$54$', is_correct: true },
      { option_key: 'B', content_vi: '$18$', content_en: '$18$', is_correct: false },
      { option_key: 'C', content_vi: '$162$', content_en: '$162$', is_correct: false },
      { option_key: 'D', content_vi: '$24$', content_en: '$24$', is_correct: false },
    ],
    solution_vi: '$u_4 = u_1 \\cdot q^3 = 2 \\cdot 3^3 = 2 \\cdot 27 = 54$.',
    solution_en: '$u_4 = u_1 q^3 = 2 \\cdot 27 = 54$.',
    correct_answer: 'A',
    math_skill: 'Tính số hạng của cấp số nhân',
    english_skill: 'GP term calculation',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-7-ds1',
    topic_id: 'top-11-2-3',
    type_id: 'type-11-7-1',
    question_type: 'TRUE_FALSE',
    format_type: 'DS',
    difficulty: 'MEDIUM',
    language_level: 2,
    question_vi: 'Cho cấp số nhân $(u_n)$ có $u_1 = 5$ và $u_2 = 10$. Xét tính đúng/sai của các mệnh đề sau:',
    question_en: 'Given a geometric progression $(u_n)$ with $u_1 = 5$ and $u_2 = 10$. Determine whether each statement is True (Đ) or False (S):',
    options: [
      { option_key: 'a', content_vi: 'Công bội của cấp số nhân là $q = 2$.', content_en: 'The common ratio is $q = 2$.', is_correct: true },
      { option_key: 'b', content_vi: 'Số hạng thứ năm là $u_5 = 80$.', content_en: 'The fifth term is $u_5 = 80$.', is_correct: true },
      { option_key: 'c', content_vi: 'Tổng của 6 số hạng đầu là $S_6 = 315$.', content_en: 'The sum of the first 6 terms is $S_6 = 315$.', is_correct: true },
      { option_key: 'd', content_vi: 'Số 160 là số hạng thứ 7 của dãy số.', content_en: 'The number 160 is the 7th term.', is_correct: false },
    ],
    solution_vi: 'a) Đúng ($q = 10/5 = 2$). b) Đúng ($u_5 = 5 \\cdot 2^4 = 80$). c) Đúng ($S_6 = \\frac{5(1 - 2^6)}{1 - 2} = 5(63) = 315$). d) Sai ($u_6 = 160$, tức là số hạng thứ 6, không phải thứ 7).',
    solution_en: 'a) True ($q = 2$). b) True ($u_5 = 80$). c) True ($S_6 = 315$). d) False ($160$ is the 6th term).',
    correct_answer: 'a-Đ, b-Đ, c-Đ, d-S',
    math_skill: 'Kiểm tra công bội và tổng n số hạng đầu CSN',
    english_skill: 'GP sum and term verification',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-11-7-tln1',
    topic_id: 'top-11-2-3',
    type_id: 'type-11-7-2',
    question_type: 'SHORT',
    format_type: 'TLN',
    difficulty: 'HARD',
    language_level: 2,
    question_vi: 'Một loài vi khuẩn sau mỗi giờ lại nhân đôi số lượng. Ban đầu trong phòng thí nghiệm có 100 con vi khuẩn. Hỏi sau 6 giờ thì số lượng vi khuẩn là bao nhiêu con?',
    question_en: 'A bacterial culture doubles every hour. If initially there are 100 bacteria, how many bacteria will there be after 6 hours?',
    solution_vi: 'Sau $n = 6$ giờ, số lượng vi khuẩn là $N = 100 \\cdot 2^6 = 100 \\cdot 64 = 6400$ con.',
    solution_en: '$N = 100 \\cdot 2^6 = 6400$ bacteria.',
    correct_answer: '6400',
    math_skill: 'Ứng dụng cấp số nhân vào sinh học',
    english_skill: 'Exponential bacterial growth',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 10 - BÀI 1: MỆNH ĐỀ VÀ TẬP HỢP (top-10-1-1 / les-10-1-1)
  // =========================================================================
  {
    id: 'q-10-1-tn1',
    topic_id: 'top-10-1-1',
    type_id: 'type-10-1-1',
    question_type: 'MCQ',
    format_type: 'TN',
    difficulty: 'EASY',
    language_level: 2,
    question_vi: 'Mệnh đề nào sau đây là mệnh đề ĐÚNG?',
    question_en: 'Which of the following propositions is TRUE?',
    options: [
      { option_key: 'A', content_vi: '$\\forall x \\in \\mathbb{R}, x^2 + 1 > 0$', content_en: '$\\forall x \\in \\mathbb{R}, x^2 + 1 > 0$', is_correct: true },
      { option_key: 'B', content_vi: '$\\exists x \\in \\mathbb{R}, x^2 < 0$', content_en: '$\\exists x \\in \\mathbb{R}, x^2 < 0$', is_correct: false },
      { option_key: 'C', content_vi: '$\\forall n \\in \\mathbb{N}, n^2 > n$', content_en: '$\\forall n \\in \\mathbb{N}, n^2 > n$', is_correct: false },
      { option_key: 'D', content_vi: '$\\pi > 4$', content_en: '$\\pi > 4$', is_correct: false },
    ],
    solution_vi: 'Vì $x^2 \\ge 0, \\forall x \\in \\mathbb{R} \\implies x^2 + 1 \\ge 1 > 0$ nên mệnh đề A đúng.',
    solution_en: '$x^2 + 1 \\ge 1 > 0, \\forall x \\in \\mathbb{R}$. Thus option A is True.',
    correct_answer: 'A',
    math_skill: 'Xác định chân trị của mệnh đề toán học',
    english_skill: 'Proposition truth value identification',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-10-1-ds1',
    topic_id: 'top-10-1-1',
    type_id: 'type-10-1-2',
    question_type: 'TRUE_FALSE',
    format_type: 'DS',
    difficulty: 'MEDIUM',
    language_level: 2,
    question_vi: 'Cho hai tập hợp $A = [-2; 3]$ và $B = (0; 5)$. Xét tính đúng/sai của các mệnh đề sau:',
    question_en: 'Given sets $A = [-2; 3]$ and $B = (0; 5)$. Determine whether each statement is True (Đ) or False (S):',
    options: [
      { option_key: 'a', content_vi: 'Giao của hai tập hợp là $A \\cap B = (0; 3]$.', content_en: 'The intersection is $A \\cap B = (0; 3]$.', is_correct: true },
      { option_key: 'b', content_vi: 'Hợp của hai tập hợp là $A \\cup B = [-2; 5)$.', content_en: 'The union is $A \\cup B = [-2; 5)$.', is_correct: true },
      { option_key: 'c', content_vi: 'Hiệu $A \\setminus B = [-2; 0)$.', content_en: 'The difference $A \\setminus B = [-2; 0)$.', is_correct: false },
      { option_key: 'd', content_vi: 'Số 3 thuộc cả hai tập hợp $A$ và $B$.', content_en: 'The number 3 belongs to both sets $A$ and $B$.', is_correct: true },
    ],
    solution_vi: 'a) Đúng. b) Đúng. c) Sai (phải là $[-2; 0]$). d) Đúng ($3 \\in [-2; 3]$ và $3 \\in (0; 5)$).',
    solution_en: 'a) True. b) True. c) False (it is $[-2, 0]$). d) True.',
    correct_answer: 'a-Đ, b-Đ, c-S, d-Đ',
    math_skill: 'Các phép toán giao, hợp, hiệu trên khoảng số',
    english_skill: 'Set operations on intervals',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-10-1-tln1',
    topic_id: 'top-10-1-1',
    type_id: 'type-10-1-3',
    question_type: 'SHORT',
    format_type: 'TLN',
    difficulty: 'MEDIUM',
    language_level: 2,
    question_vi: 'Lớp 10A có 40 học sinh, trong đó có 25 học sinh thích môn Toán và 20 học sinh thích môn Tiếng Anh. Biết rằng có 12 học sinh thích cả hai môn. Hỏi có bao nhiêu học sinh không thích môn nào trong hai môn trên?',
    question_en: 'In a class of 40 students, 25 like Math and 20 like English. 12 students like both subjects. How many students do not like either subject?',
    solution_vi: 'Số học sinh thích ít nhất 1 môn là: $|A \\cup B| = 25 + 20 - 12 = 33$ học sinh.\nSố học sinh không thích môn nào là: $40 - 33 = 7$ học sinh.',
    solution_en: 'Students liking at least one subject: $25 + 20 - 12 = 33$. Disliking both: $40 - 33 = 7$.',
    correct_answer: '7',
    math_skill: 'Ứng dụng biểu đồ Venn đếm phần tử',
    english_skill: 'Venn diagram counting',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },

  // =========================================================================
  // LỚP 10 - BÀI 6: HÀM SỐ BẬC HAI (top-10-6-1 / les-10-6-1)
  // =========================================================================
  {
    id: 'q-10-6-tn1',
    topic_id: 'top-10-6-1',
    type_id: 'type-10-6-1',
    question_type: 'MCQ',
    format_type: 'TN',
    difficulty: 'EASY',
    language_level: 2,
    question_vi: 'Toạ độ đỉnh $I$ của parabol $y = x^2 - 4x + 3$ là:',
    question_en: 'The coordinates of the vertex $I$ of the parabola $y = x^2 - 4x + 3$ are:',
    options: [
      { option_key: 'A', content_vi: '$I(2; -1)$', content_en: '$I(2, -1)$', is_correct: true },
      { option_key: 'B', content_vi: '$I(-2; 15)$', content_en: '$I(-2, 15)$', is_correct: false },
      { option_key: 'C', content_vi: '$I(4; 3)$', content_en: '$I(4, 3)$', is_correct: false },
      { option_key: 'D', content_vi: '$I(2; 1)$', content_en: '$I(2, 1)$', is_correct: false },
    ],
    solution_vi: '$x_I = -\\frac{b}{2a} = 2, y_I = (2)^2 - 4(2) + 3 = -1 \\implies I(2; -1)$.',
    solution_en: 'Vertex $x = 2, y = -1 \\implies I(2, -1)$.',
    correct_answer: 'A',
    math_skill: 'Tìm toạ độ đỉnh Parabol',
    english_skill: 'Parabola vertex computation',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-10-6-ds1',
    topic_id: 'top-10-6-1',
    type_id: 'type-10-6-2',
    question_type: 'TRUE_FALSE',
    format_type: 'DS',
    difficulty: 'MEDIUM',
    language_level: 2,
    question_vi: 'Cho tam thức bậc hai $f(x) = x^2 - 5x + 6$. Xét tính đúng/sai của các mệnh đề sau:',
    question_en: 'Given the quadratic trinomial $f(x) = x^2 - 5x + 6$. Determine whether each statement is True (Đ) or False (S):',
    options: [
      { option_key: 'a', content_vi: 'Tam thức $f(x)$ có hai nghiệm phân biệt là $x = 2$ và $x = 3$.', content_en: 'The trinomial has two distinct roots: $x = 2$ and $x = 3$.', is_correct: true },
      { option_key: 'b', content_vi: 'Ta có $f(x) < 0$ với mọi $x \\in (2; 3)$.', content_en: 'We have $f(x) < 0$ for all $x \\in (2; 3)$.', is_correct: true },
      { option_key: 'c', content_vi: 'Bất phương trình $x^2 - 5x + 6 \\ge 0$ có tập nghiệm là $[2; 3]$.', content_en: 'The inequality $x^2 - 5x + 6 \\ge 0$ has solution set $[2; 3]$.', is_correct: false },
      { option_key: 'd', content_vi: 'Giá trị nhỏ nhất của $f(x)$ trên $\\mathbb{R}$ là $-\\frac{1}{4}$.', content_en: 'The global minimum value of $f(x)$ is $-\\frac{1}{4}$.', is_correct: true },
    ],
    solution_vi: 'a) Đúng. b) Đúng (trong khoảng 2 nghiệm trái dấu $a=1>0$). c) Sai (tập nghiệm là $(-\\infty; 2] \\cup [3; +\\infty)$). d) Đúng ($f(5/2) = -1/4$).',
    solution_en: 'a) True. b) True. c) False. d) True ($f(2.5) = -0.25$).',
    correct_answer: 'a-Đ, b-Đ, c-S, d-Đ',
    math_skill: 'Xét dấu tam thức bậc hai và giải BPT',
    english_skill: 'Quadratic sign and inequality verification',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-10-6-tln1',
    topic_id: 'top-10-6-1',
    type_id: 'type-10-6-3',
    question_type: 'SHORT',
    format_type: 'TLN',
    difficulty: 'HARD',
    language_level: 2,
    question_vi: 'Một quả bóng được đá lên từ mặt đất với quỹ đạo chuyển động có độ cao tính theo thời gian $t$ (giây) là $h(t) = -5t^2 + 20t$ (mét). Độ cao cực đại mà quả bóng đạt được là bao nhiêu mét?',
    question_en: 'A ball is kicked upwards such that its height at time $t$ (seconds) is $h(t) = -5t^2 + 20t$ (meters). What is the maximum height in meters reached by the ball?',
    solution_vi: '$h(t)$ là hàm bậc hai có đỉnh tại $t = -\\frac{20}{2(-5)} = 2$ giây. Độ cao cực đại là $h(2) = -5(4) + 20(2) = 20$ mét.',
    solution_en: 'Vertex occurs at $t = 2$s. Maximum height $h(2) = 20$ meters.',
    correct_answer: '20',
    math_skill: 'Bài toán cực trị parabol thực tế',
    english_skill: 'Projectile maximum height problem',
    status: 'PUBLISHED',
    created_by: 'usr-teacher-1',
    created_at: new Date().toISOString(),
  },
];

// Helper functions for fallback retrieval
export function getQuestionsForLesson(lessonId: string, topicId?: string): Question[] {
  return FULL_QUESTION_BANK.filter((q) => {
    if (topicId && q.topic_id === topicId) return true;
    if (lessonId && q.id.includes(lessonId.replace('les-', 'q-'))) return true;
    return false;
  });
}

export function getWorkedExamplesForLesson(lessonId: string): WorkedExample[] {
  return DEFAULT_WORKED_EXAMPLES[lessonId] || [];
}
